### ISSUE TITLE
Support `Int32` Case for Indices in AMD Family of Algorithms

### ISSUE THREAD

**Issue by RoyiAvital** [DrTimothyAldenDavis/SuiteSparse#105]
Currently, the code in AMD family (C Code) use `Int` to define the indices of the data:

![image](https://user-images.githubusercontent.com/7347975/134305543-abdf311c-2cf1-4056-9ff3-335101196295.png)

From `amd_internal.h` one could see that `Int` is defined as `SuiteSparse_long`:

![image](https://user-images.githubusercontent.com/7347975/134305645-f119afcb-7670-46b3-9856-e989d1b9b62b.png)

Namely it is a 64 Bit Integer on all systems.  

The feature request is having a version of the functions which assumes the input matrix is defined by 32 Bit integers. Hence all the workspace and all buffers can be 32 Bit integers (`Int32`).

This can improve performance greatly for matrices with up to `2 ^ 31 - 1` elements (For matrix with `Float64` elements it means a matrix of size more than `16 GB`). Which is probably what everyone using SparseSuite on workstation / desktop / laptop could be done with.

In return, it means the data is smaller, better cache locality, less burden on the memory system and where `SIMD` is applicable, we get faster throughput.

It seems the definitions of most variables are done using macros hence it might be done pretty easily.

**Remark**: I only looked at the `C` codes as I have no experience with `FORTRAN`.

**Comment by DrTimothyAldenDavis** [comment]
You've misread the code.  AMD_1 is compiled twice, with 32bit and 64bit
integers.  After running "make" see the Demo/my_amd_demo.out and note that
it states (see the "size of AMD integer"):

AMD version 2.4.6, date: May 4, 2016
AMD demo, with the 24-by-24 Harwell/Boeing matrix, can_24:

AMD version 2.4.6, May 4, 2016: approximate minimum degree ordering
    dense row parameter: 10
    (rows with more than max (10 * sqrt (n), 16) entries are
    considered "dense", and placed last in output permutation)
    aggressive absorption:  yes
    size of AMD integer: 4

and contrast with my_amd_l_demo.out
