### ISSUE TITLE
Cannot finish installation when the LAPACK and BLAS are not on default path

### ISSUE THREAD

**Issue by qq1012510777** [DrTimothyAldenDavis/SuiteSparse#106]
Hi. I do not have root. So I first installed blas and lapack on my self-defined folder.

Then I downloaded SUITESPARSE, and `cd SuiteSparse-5.10.1`, and then

`make -lgfortran BLAS='/home/m3/lapack-3.10.0/lib/libblas.a -fPIC' LAPACK='/home/m3/lapack-3.10.0/lib/liblapack.a -fPIC'`

then I got

`xerbla.f:(.text+0x55): undefined reference to `_gfortran_st_write' `

`/usr/bin/ld: xerbla.f:(.text+0x60): undefined reference to `_gfortran_string_len_trim'\`

`/usr/bin/ld: xerbla.f:(.text+0x7a): undefined reference to `_gfortran_transfer_character_write'\`

`/usr/bin/ld: xerbla.f:(.text+0x8a): undefined reference to `_gfortran_transfer_integer_write'\`

`/usr/bin/ld: xerbla.f:(.text+0x92): undefined reference to `_gfortran_st_write_done'\`

`/usr/bin/ld: xerbla.f:(.text+0x9d): undefined reference to `_gfortran_stop_string'\`

I added `-lgfortran` and `-fPIC` because someone said they may help, but actually not. Is my way of `make` wrong?

**Comment by DrTimothyAldenDavis** [comment]
You have to add /home/m3/lapack-3.10.0/lib to your LD_LIBRARY_PATH.

**Comment by qq1012510777** [comment]
Thanks for your reply. I just want to use SUITESPARSE in our cluster. As you said, I run `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/torresLab/yintingchang/lapack-3.10.0/lib` and `export LIBRARY_PATH=$LIBRARY_PATH:/home/torresLab/yintingchang/lapack-3.10.0/lib`. Then I run `echo $LD_LIBRARY_PATH` and `echo $LIBRARY_PATH`, I got

`/opt/slurm/lib:/opt/slurm/lib/slurm::/home/torresLab/yintingchang/lapack-3.10.0/lib` and `:/home/torresLab/yintingchang/lapack-3.10.0/lib`.

Then I just run `make` (since the path is added). I got a lot of `relocation R_X86_64_32 against `.rodata'` as follows

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(dpotrf.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(dpotrf2.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(zpotrf.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(zpotrf2.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(ilaenv.f.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/liblapack.a(xerbla.f.o): relocation R_X86_64_32S against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(dgemv.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(dtrsv.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(dgemm.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(dsyrk.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(dtrsm.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(zgemv.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(ztrsv.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(zgemm.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(ztrsm.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: /home/torresLab/yintingchang/lapack-3.10.0/lib/libblas.a(zherk.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

`/usr/bin/ld: final link failed: Nonrepresentable section on output`

`collect2: error: ld returned 1 exit status`

`make[3]: *** [Makefile:544: /home/torresLab/yintingchang/SuiteSparse/lib/libcholmod.so.3.0.14] Error 1`

`make[3]: Leaving directory '/home/torresLab/yintingchang/SuiteSparse/CHOLMOD/Lib'`

`make[2]: *** [Makefile:31: library] Error 2`

`make[2]: Leaving directory '/home/torresLab/yintingchang/SuiteSparse/CHOLMOD/Lib'`

`make[1]: *** [Makefile:14: all] Error 2`

`make[1]: Leaving directory '/home/torresLab/yintingchang/SuiteSparse/CHOLMOD'`

`make: *** [Makefile:25: go] Error 2`

**Comment by DrTimothyAldenDavis** [comment]
You’re trying to use a static .a library. The make file assumes a .so. --
Sent from Gmail Mobile

**Comment by qq1012510777** [comment]
Yes! thanks! I also noticed that.



> You’re trying to use a static .a library. The make file assumes a .so. -- Sent from Gmail Mobile

**Comment by qq1012510777** [comment]
I'd like to share my experience on installing SUITESPARSE in supercomputer, i.e., without root. Hope it is helpful.

First, download the [lapack-3.10.0.tar.gz](http://performance.netlib.org/lapack/#_lapack_version_3_10_0_2) here and extract it. Then `cd lapack && mkdir build`. Then, open `CMakeLists.txt`, find `option(BUILD_SHARED_LIBS "Build shared libraries" OFF)` and change this line to `option(BUILD_SHARED_LIBS "Build shared libraries" ON)`, namely, build dynamic library!

Then, things go easy. Just `cd build`, `cmake -DCMAKE_INSTALL_LIBDIR=/your/path/install/lapackLib ..`, `make` and `make install`. After these steps, you will find `libblas.so` and `liblapack.so`, etc, in your defined path.

Then, `cd Suitesparse`. Now, time to add your `/your/path/install/lapackLib`. Do `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/path/install/lapackLib` and `export LIBRARY_PATH=$LIBRARY_PATH:/your/path/install/lapackLib`. Finally, just `make`.
