### ISSUE TITLE
Request for easy overriding of CUDA capabilities

### ISSUE THREAD

**Issue by mikepurvis** [DrTimothyAldenDavis/SuiteSparse#112]
Related to https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/56#issuecomment-825933064, there are two places in the SuiteSparse source when `nvcc` gencode flags are hard-coded into build scripts. This is unfortunate not just from a maintenance point of view but it makes patching these for packaging/vendoring purposes more difficult and fragile:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/9d97e0a2fb3d03fac66cd45d3a84338b0a97f368/SuiteSparse_config/SuiteSparse_config.mk#L263-L267

It would be great if this could be parameterized as a define/envvar/file that could be used to list the specific ones requested for a given build of SuiteSparse. CMake, for example, handles this using the `CUDA_ARCHITECTURES` property, which can be set at configure time:

https://cmake.org/cmake/help/git-stage/prop_tgt/CUDA_ARCHITECTURES.html

**Comment by DrTimothyAldenDavis** [comment]
Yes, it's on my TODO list.  I need a CMake script for all of SuiteSparse, and cmake now has better support for CUDA (as of cmake 3.17).  I'm using CMake + CUDA in my draft GraphBLAS CMakelists.txt and it's working well there.  Once that is stable I will write a full cmake build system for SuiteSparse.  I don't intend on fixing or patching SuiteSparse_config.mk.  I plan on scrapping it entirely and replacing it with cmake.

**Comment by DrTimothyAldenDavis** [comment]
I'll keep this open until I handle the cmake for suiteSparse.

**Comment by gruenich** [comment]
Have you considered to develop the improved CMake support in a public branch? Then other can follow your development, give early feedback, and might even help you. You could create one module the way you want it to be and other might pick up not yet modernized modules and help you out? Do you want to try this?

**Comment by DrTimothyAldenDavis** [comment]
I'm working on the CMake build system for related packages (LAGraph and GraphBLAS), and how they interact with each other.  Once I figure out the best way to set that up, I'll write a CMake build system for all of SuiteSparse.

**Comment by DrTimothyAldenDavis** [comment]
The CMake build system is ready for a beta release.  It was on the dev2 branch and now on the default 'master' branch.  I'll tag a beta release of SuiteSparse 6.0.0 shortly.

You can define the build token SUITESPARSE_CUDA_ARCHITECTURES. 

See the new SuiteSparse_config and in particular, this block of code.
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/4aa5a7382835986d33aee37c16882c108527b50f/SuiteSparse_config/cmake_modules/SuiteSparsePolicy.cmake#L134
