### ISSUE TITLE
One-line queries of the SuiteSparse matrix collection

### ISSUE THREAD

**Issue by denis-bz** [DrTimothyAldenDavis/SuiteSparse#130]
Hello Prof. Davis,

Fwiw, here's a one-page [gist](https://gist.github.com/denis-bz/6a363b3f353f9cc3310b1be40710a22d) that uses python pandas for simple queries like
```
'(posdef == 1)  &  (1000 <= rows <= 20000)'
'(symm == 1)  &  (posdef == 0)' 
```
It just queries to a subset csv -- it doesn't download like ssgetpy.

Bytheway, there are quite a few duplicate id s in ssstats.csv ?

(This is not really an issue -- move it to [Discussions](https://docs.github.com/en/discussions) ?)

cheers
  -- denis

**Comment by DrTimothyAldenDavis** [comment]
the sstats.csv file does list the id's of the matrices.  The row in the table is the ID (offset by 1).  So row 3 contains the HB/1138_bus matrix, with id of zero.  I don't have a good place in my documentation where I defined the content of this csv file.  It's created here:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/MATLAB_Tools/SuiteSparseCollection/sscsv_write.m

This fprintf shows all the fields in a single line of the file:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/2aa5234e777f169936972cd935c5a723ff473ff6/MATLAB_Tools/SuiteSparseCollection/sscsv_write.m#L20-L33
