### ISSUE TITLE
[UMFPACK] In-memory `save` and `load` for numeric and symbolic

### ISSUE THREAD

**Issue by rayegun** [DrTimothyAldenDavis/SuiteSparse#133]
We have a need to 
1. copy `umfpack_numeric` and `umfpack_symbolic` types and
2.  serialize them in memory. 

Both of these things can be done by an in-memory `save` and `load`, which do exactly as the current methods do, but which take/return a UInt8 buffer (and the size of that buffer) rather than a filename.

Is this something easy to add? We would use the feature immediately if so.

**Comment by DrTimothyAldenDavis** [comment]
I don't think it would be very hard to add these features, particularly if I don't include compression like I do for the serialized blob for GraphBLAS.  I'll add it to my TODO list.

**Comment by DrTimothyAldenDavis** [comment]
This now appears in UMFPACK 6.3.0, in SuiteSparse 7.4.0, in the default dev branch of the SuiteSparse repo.  I'll release a 7.4.0.beta1 soon so I'll go ahead and close this issue.
