### ISSUE TITLE
Error on solving large sparse matrix

### ISSUE THREAD

**Issue by Airbala** [DrTimothyAldenDavis/SuiteSparse#137]
**Describe the bug**
CHOLMOD error: problem too large.

**To Reproduce**
CHOLMOD sparse:  A:  1437960-by-1437960, nz 32297325, upper.  OK

**Screenshots**
<img width="848" alt="image" src="https://user-images.githubusercontent.com/39217135/195029692-95a0c27a-ce52-4e8e-8602-5c433f06ef6b.png">

**Desktop (please complete the following information):**
 - OS: linux
 - compiler gvv
 - BLAS and LAPACK library, if applicable
 - Version 5.13.0

**Additional context**
cholmod version 3.0.14, I want to solve large sparse matrix

**Comment by DrTimothyAldenDavis** [comment]
You're trying to use the 32-bit version on a problem that is too big for 32-bit integer.  It requires the 64-bit version.  Try the cholmod_l_* methods instead.
