### ISSUE TITLE
Incorrect pointer assignment in umf_kernel_init 

### ISSUE THREAD

**Issue by advanpix** [DrTimothyAldenDavis/SuiteSparse#138]
Pointers Rpi & Rpx are assigned to incorrect memory blocks.

```
rpi = UMF_mem_alloc_tail_block (Numeric, UNITS (Int *, n_row+1)) ;
rpx = UMF_mem_alloc_tail_block (Numeric, UNITS (Entry *, n_row+1)) ;
...
Rpi = (Int   **) (Memory + rpx) ; <--
Rpx = (Entry **) (Memory + rpi) ; <--
```

Should be:
```
Rpi = (Int   **) (Memory + rpi) ;
Rpx = (Entry **) (Memory + rpx) ;
```

The bug reveals itself if `UNITS (Int *, n_row+1) != UNITS (Entry *, n_row+1)`.

**Comment by DrTimothyAldenDavis** [comment]
This proposed fix does correct the confusion between Rpi and Rpx, but https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/2a35c27b9f2d50383501e7f62027b9098707ac21 is the complete fix.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback!

**Comment by advanpix** [comment]
> This proposed fix does correct the confusion between Rpi and Rpx, but [2a35c27](https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/2a35c27b9f2d50383501e7f62027b9098707ac21) is the complete fix.

Well, this is interesting. You just took the results of my work and made commit under your name. 
Basically you just stripped my authorship to make my contribution to the project untraceable.
This is the worst policy of accepting the contributions in open-source world I have ever seen.

You should clearly state this on the main page of the repository.

**Comment by DrTimothyAldenDavis** [comment]
Your proposed fix was in the right direction, but broken, so I couldn't merge it as-is so I fixed the problem in a different way.  I'm happy to credit you for pointing out the problem.  I do have a contributor policy posted (which wasn't followed).  I require a signed contributor agreement for all PRs.  That requirement is stated when you do a pull request.

I'll back out the changes.  If you'd like to propose them, please sign a contributor agreement and do another PR.
