### ISSUE TITLE
How to run CHOLMOD with single thread?

### ISSUE THREAD

**Issue by Airbala** [DrTimothyAldenDavis/SuiteSparse#140]
**Describe the bug**
How to use CHOLMOD with single thread?

**Screenshots**
<img width="594" alt="image" src="https://user-images.githubusercontent.com/39217135/197722497-309c44d2-82d1-4ada-92d1-979135f6d7f9.png">

**Desktop (please complete the following information):**
 - OS: linux
 - compiler gcc
 - BLAS and LAPACK library, if applicable 
 - Version OpenBLAS

**Additional context**
When I run the demo program to solve a large sparse matrix, the program will start about 30 threads to factorize the matrix. I want to test CHOLMOD with single thread, Is there an enviornment variable to control this? thanks very much!

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback.  There's a way to do it but it requires a recompilation of CHOLMOD.  There's a #define in the current version (see Include/cholmod.h, or Config/cholmod.h.in in the current beta7 version).  That can be redefined at compile time with -DCHOLMOD_OMP_NUM_THREADS=1.  But that is too limiting, so I'm adding a run-time control (Common->nthreads_max).  I'll add that in the final release of SuiteSparse v6.0.0.

**Comment by DrTimothyAldenDavis** [comment]
This should be resolved with the new setting:  Common->nthreads_max = 1, in SuiteSparse v6.0.0.  Thanks again for the input.
