### ISSUE TITLE
Calling cholmod_l_factorize() twice generates cuBLAS error

### ISSUE THREAD

**Issue by Leqq** [DrTimothyAldenDavis/SuiteSparse#141]
I am trying to use cuda to accelarate supernodal cholesky, but it seems I can only call cholmod_l_factorize() once with the same factor during the living scope of a cholmod_common. I tried cuda 11.0, 11.2, 11.6 and 11.8, and it turns out that's always the case. My test code is 

![Screenshot from 2022-11-03 18-26-13](https://user-images.githubusercontent.com/115964040/199699272-9c435f43-77b9-40a9-84ab-242088449a55.png)

and the error is 

CHOLMOD sparse:  A:  18000-by-18000, nz 3457658, upper.  OK
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
CHOLMOD error: GPU CUBLAS stream. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 504
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 538
CHOLMOD error: GPU CUBLAS routine failure. file: ../Supernodal/../GPU/t_cholmod_gpu.c line: 595
Time: 3270.9850 ms

**Comment by DrTimothyAldenDavis** [comment]
Sorry for the long turn-around time to resolve this issue.  I think I've finally fixed this in my latest revision (in the dev2 branch of SuiteSparse, not yet posted as a stable release).

**Comment by DrTimothyAldenDavis** [comment]
Fixed in SuiteSparse 7.4.0.
