### ISSUE TITLE
Problem installing UMPACK, CHOLMOD, KLU, and SuiteSparseQR in Matlab R2018a

### ISSUE THREAD

**Issue by AntonSemechko** [DrTimothyAldenDavis/SuiteSparse#16]
**Describe the bug**
UMPACK, CHOLMOD, KLU, and SuiteSparseQR not being installed due to recurrent error with \metis-5.1.0\gk_arch.h (screen shot attached)

**To Reproduce**
Enter `SuiteSparse_install` into Matlab command window

**Expected behavior**
All components of SuiteSparse should install\compile without errors 

**Screenshots**
![SuiteSparse installation issues](https://user-images.githubusercontent.com/13392426/71278730-621cb780-2326-11ea-881e-1387a08d3607.jpg)

**Desktop:**
- OS: Windows 8.1 64-bit
- C & C++ Compiler: MinGW64 
- Matlab Version: 9.4.0.813654 (R2018a)
- BLAS version: Intel MKL Version 2017.0.31 Product Build 20170606 for Intel(R) 64 architecture applications, CNR branch AVX2
-LAPACK version: Intel MKL Version 2017.0.31 Product Build 20170606 for Intel(R) 64 architecture applications, CNR branch AVX2, Linear Algebra PACKage Version 3.7.0

**Comment by DrTimothyAldenDavis** [comment]
This is a limitation of metis, which I can't work around.  To resolve it, simply compile without it.  You can do this just by deleting the metis folder from SuiteSparse.

**Comment by AntonSemechko** [comment]
Thank you for the prompt response!

I followed your suggestion. KLU was successfully compiled as a result, but installations of UMFPACK, CHOLMOD, and SuiteSparseQR still failed due to following errors in the umfpack_make.m, cholmod_make.m, and spqr_make.m files when calling mex

gcc: error: libmwlapack.lib: No such file or directory
gcc: error: libmwblas.lib: No such file or directory

**Comment by DrTimothyAldenDavis** [comment]
That's not a problem with SuiteSparse, but with MATLAB.

Those are libraries that MathWorks provides with MATLAB, but in each
release of
MATLAB, they change how to link against them.  I can't keep up with their
changes,
unfortunately.  The MATLAB documentation might provide some guidance on how
to
link against LAPACK and the BLAS libraries.

**Comment by AntonSemechko** [comment]
Ok, I will look into that. Thanks for your help!
