### ISSUE TITLE
Use `suitesparse` prefix for include directories in 6.0.0

### ISSUE THREAD

**Issue by alsora** [DrTimothyAldenDavis/SuiteSparse#177]
**Is your feature request related to a problem? Please describe.**

Hi, I'm testing the new 6.0.0 version (using hash d42beebdcc6b98c7fb2f7f2927f32c19e0f602d0).
I noticed that when building it, the header files get installed to paths like `/usr/local/include/cholmod.h`.
On the other hand, when installing older versions from debian packages (i.e. `sudo apt-get install libsuitesparse-dev`), they would get installed as `/usr/include/suitesparse/cholmod.h`.

**Describe the solution you'd like**

IMO it would be preferred to keep the `suitesparse` prefix, rather than dumping all the headers in the "global" `/usr/local/include` directory.
Besides breaking compatibility with the debian package version, the current approach results in setting CMake variables such as `CHOLMOD_INCLUDE_DIR` to `/usr/local/include`.
This means that when in my project I do `target_include_directories(my_target PUBLIC ${CHOLMOD_INCLUDE_DIR})` I'm potentially including also a lot of unrelated stuffs (i.e. everything that is in `/usr/local/include`; the lack of a `suitesparse` directory does not allow for any more fine-grained control).

This should be a simple enough improvement.

An even better, although more complex, improvement would be using modern CMake targets and separate (per-project) include directories.

This would result, eventually, in allowing users to do in their `CMakeLists.txt`
```
find_package(CHOLMOD REQUIRED)
target_link_libraries(my_target PUBLIC CHOLMOD::CHOLMOD)
```
and in their source code
```
#include <CHOLMOD/cholmod.h>
```

See how by linking with a "modern cmake target", I automatically get access to its include directories.
Moreover, using per-project include directories we would allow users to build everything that is in suitesparse, but control with per-target precision which header files are accessible.

**Describe alternatives you've considered**

Note that I tried to install the header files to a `suitesparse` subdirectory, but this caused issues with the `Find*` cmake modules, which failed to find the header files.

Let me know what do you think and I'm willing to try to implement some of these features.

**Comment by DrTimothyAldenDavis** [comment]
I'm doing the standard cmake thing (at least I thing I am), with the line:

`include ( GNUInstallDirs )`

So that would place all the packages in the standard place.  If the end user or Linux distro maintainer wants to install in a different place, they can change the CMAKE_INSTALL_PREFIX, right?  Isn't that the cmake way of doing things?

If I deviate from that, it might mess up the Linux distros.

**Comment by DrTimothyAldenDavis** [comment]
I'm guessing that the Linux distro maintainers will use the CMAKE_INSTALL_PREFIX if they want to keep all the code in /usr/include/suitesparse.

**Comment by fabiencastan** [comment]
With CMAKE_INSTALL_PREFIX, it is not possible to modify the include folder.
All libraries are not doing it, but AFAIK it is more standard for each library to install:
```
{CMAKE_INSTALL_PREFIX}/include/suitesparse/SuiteSparse_config.h
{CMAKE_INSTALL_PREFIX}/${LIBDIR}/libsuitesparse.so
```
This good practice avoids conflicts between header files from different libraries (as it simply avoids to put all headers of all libraries in the same "include" folder).

**Comment by alsora** [comment]
Yes, as @fabiencastan said, that's not exactly how `CMAKE_INSTALL_PREFIX` works.
Using Linux as an example, `CMAKE_INSTALL_PREFIX` defaults to `/usr/local` and indeed currently we have files installed such as `usr/local/include/amd.h` and `usr/local/lib/libamd.so`.
By modifying `CMAKE_INSTALL_PREFIX`, we can replace the `/usr/local` base path with something else (for example `/my/path` or `/usr/local/suitesparse`) 

With the suitesparse debian package, we have that the public header files are inside this `suitesparse` directory (e.g. as `/usr/include/suitesparse/amd.h`), while libraries and other artifacts do not have any intermediate directory (e.g. as `/usr/lib/libamd.so`).
I think that this makes sense because libraries can be individually picked up, while for header files we just specify the parent directory.

Note that a directory-structure like the one that the debian package produces can be obtained by modifying `CMAKE_INSTALL_INCLUDEDIR`: this is one of the variables defined by `include ( GNUInstallDirs )` and it defaults to `include`.
This means that the absolute path of installed header files is something like `${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}`.
Thus, this variable could be changed from `include` to `include/suitesparse`.

However, this change alone is not sufficient to get everything working. At the very least, some small changes are needed in  the `Find*` cmake files.
Moreover I would argue that the directory structure should be preserved between build and install locations, thus modifying also the source code of this repository to have header files in places such as `AMD/Include/suitesparse/amd.h` rather than the current `AMD/Include/amd.h`.

---- 

With all this very long premise, I'm suggesting to take advantage of this 6.0.0 beta version and its transition to CMake to follow CMake and packaging best-practices. Or at least to take a step in that direction.

Modern CMake packages should export targets (e.g. `suitesparse::AMD` or `AMD::AMD`) that dependent applications can just link to with `target_link_libraries(my_target PUBLIC AMD::AMD)`, and this should be the only necessary step to use the library, without having to deal with variables like `${AMD_INCLUDE_DIR}` and `${AMD_LIBRARY}` (with these names also being not fully standardized, some places packages use plurals, some singulars, etc causing potential confusion).

Header files should be placed in intermediate, project-specific, directories to avoid clashes.
IMHO Having to use something like `#include "amd.h"` in a project that depends on suitesparse, is almost a code-smell: it does not provide context about from which package this header file comes from, differently from something like `#include "suitesparse/amd.h`, and it is indeed associated to potentially bad/dangerous practices of projects installing all their files and artifacts into global directories (e.g. `/usr/include`) rather than in project specific ones,

**Comment by StefanBruens** [comment]
Please don´t concatenate multiple `CMAKE_INSTALL_*` variables, that is just plain wrong. These variables are allowed to contain either absolute or relative paths.

To preserve the current behavior, just use:  
`install( .... DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/suitesparse)`

`install` automatically adds `CMAKE_INSTALL_PREFIX` iff `CMAKE_INSTALL_INCLUDEDIR` is a relative path.

**Comment by DrTimothyAldenDavis** [comment]
If I was starting from scratch, asking the end user to write

#include <suitesparse/amd.h>

in their code sounds reasonable. It would make it clear in the user program where AMD, CHOLMOD, UMFPACK, etc come from, and how they are inter-related, and it would add some nice organization to the top-level system include file (/usr/local/include for example). 
 But at this point there are too many packages out there that just do

#include <amd.h>

and it would be too disruptive to change that.  So as useful as this would be, I'm stuck with my existing framework.
