### ISSUE TITLE
Performance difference CHOLMOD GPL vs. LPGL

### ISSUE THREAD

**Issue by Fabian188** [DrTimothyAldenDavis/SuiteSparse#182]
When I understand it right, the CHOLMOD lib can be built as LGPL and GPL and depending on the setting different features are added. 

I understand the legal difference between these two licenses. But what are differences w.r.t. the performance of CHOLMOD? Is there any study available or do I need to do the performance tests myself? I assume this to be not so easy when I don't know where to look at.

Thanks very much for the software! We used a very old SuiteSparse/Metis and METIS crashed on my arm64 MacBook. The new code works and a 3D FEM benchmark on the MacBook is faster than a quite expensive AMD EPYC 7F32 8-Core Processor (2020) (OpenBLAS vs. MKL).

**Comment by DrTimothyAldenDavis** [comment]
That's correct.  Some CHOLMOD modules are LGPL, and some are GPL.  The modules have different authors and even different copyright (Core and Partition are copyrighted by the Univ of Florida, the others are copyrighted by their authors).

The Supernodal module is GPL and it is what makes CHOLMOD very fast for large problems (up to 10x faster).  For modest-sized problems, CHOLMOD would automatically select the simplicial method in the CHOLMOD:Cholesky module.  So it depends on the usage of CHOLMOD.

The ACM TOMS paper: https://doi.org/10.1145/1391989.1391995 has a performance comparson.

Figure 2 is the key result (below). The x axis is the computational intensity (flop count divided by nnz(L)).  That's something that the symbolic analysis computes, and it is a very good predictor of the performance of the numerical phase.  You could check it on any given matrix.  The y axis is the relative performance.  When flop/nnz(L) is > 40, then then supernodal method is faster.

![image](https://user-images.githubusercontent.com/19956793/204034543-900180e1-236a-4ef4-b340-8e8746a93e94.png)

The CHOLMOD:Modify module is GPL as well.  This provides update/downdate methods (for low-rank changes).  There is no LGPL equivalent in CHOLMOD.

**Comment by Fabian188** [comment]
Thank you very much for the explanation and the nice comprehensive paper!
