### ISSUE TITLE
SPEX not building on MINGW32 and MINGW64

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [DrTimothyAldenDavis/SuiteSparse#193]
The SPEX libary is not building on the MINGW* build systems on Windows.  It builds fine on Windows with MINGW when using clang.

@mmuetzel : is this an issue with the new build.yaml?

**Comment by mmuetzel** [comment]
See #184:
> Edit: The GCC environments (MINGW64 and MINGW32) are currently failing to build SPEX because of a downstream issue with mpfr.

This is still the same issue. We could disable building SPEX for those environments for the time being if you prefer.

**Comment by DrTimothyAldenDavis** [comment]
Yes -- I would prefer if the build of SPEX could be disabled on gcc + mingw, until the mpfr issue is fixed.

Thanks!

**Comment by DrTimothyAldenDavis** [comment]
Fixed in https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/201 which disables the build of SPEX for MINGW*.  Once the MPFR issue is resolved for those platforms, this change can be reverted so SPEX can be built again in this CI test.

**Comment by DrTimothyAldenDavis** [comment]
I'll leave this issue open to remind me that the build.yaml should be revised to re-enable the build of SPEX once it works on MINGW*.

**Comment by mmuetzel** [comment]
This issue can probably be closed now that #214 has been merged.
