### ISSUE TITLE
error run cholmod_super_numeric with GPU_BLAS

### ISSUE THREAD

**Issue by zjd1988** [DrTimothyAldenDavis/SuiteSparse#20]
I have modified ceres witch used by colmap(https://github.com/colmap/colmap) to use suitesparse(with GPU accelerating).

but I encountered a problem:
**CHOLMOD (gpu_updateC)** function return error in t_cholmod_gpu.c  line 504 
I added some logs to show cublashandle which was NULL.

Then, I traced **CHOLMOD (gpu_updateC)** which called by **TEMPLATE (cholmod_super_numeric)**

there are gpu_init and gpu_end in **TEMPLATE (cholmod_super_numeric)**, but i didn't see any initialize cublashandle in gpu_init.

Is this a problem?

**Comment by DrTimothyAldenDavis** [comment]
Sorry for the long turn-around time to resolve this issue.  I think I've fixed it in my latest commits to the dev2 branch of SuiteSparse.  I'll post a beta release shortly.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in SuiteSparse 7.4.0.
