### ISSUE TITLE
Hierarchical hypersparse matrices?

### ISSUE THREAD

**Issue by alexandergunnarson** [DrTimothyAldenDavis/SuiteSparse#222]
**Is your feature request related to a problem? Please describe.**
This is part of a series of questions (and corresponding feature requests) relating to scaling a graph DB based on SuiteSparse:GraphBLAS. It identifies a potential opportunity for performance enhancement.

**Describe the solution you'd like**
I understand SuiteSparse:GraphBLAS gives the option of using hypersparse matrices. I came across a paper you (@DrTimothyAldenDavis) co-authored (["75,000,000,000 Streaming Inserts/Second Using Hierarchical Hypersparse GraphBLAS Matrices" (2020)](https://arxiv.org/pdf/2001.06935.pdf)) that takes the concept of a hypersparse matrix and adds to it the concept of hierarchicality, which "ensure[s] that the majority of updates are performed in fast memory" (see the screenshot further below).

Is this hierarchicality a feature of SuiteSparse:GraphBLAS hypersparse matrices, or is it an additional enhancement that has yet to be implemented? If it's already packaged into the CPU implementation, I'm curious — would it make sense to take the same approach in a GPU implementation?

**Describe alternatives you've considered**
It may be possible to use non-hierarchical hypersparse matrices in SuiteSparse:GraphBLAS. However, without knowing the implementation details, I'm not sure.

**Additional context**
<img width="1341" alt="Screen Shot 2022-12-14 at 11 46 32 PM" src="https://user-images.githubusercontent.com/4691106/207791646-936afeea-7565-4530-b4a0-e8b229183cf5.png">

**Comment by DrTimothyAldenDavis** [comment]
GraphBLAS doesn't use hierarchical matrices internally (either on the CPU or GPU).  The hierarchical matrices are just how GraphBLAS is used.  Those matrices A, A1, A2, etc are each their own GrB_Matrix, in the work with MIT Lincoln Lab.

I don't have plans to add support for hierarchical matrices internally in GraphBLAS.  The MIT application uses a small subset of GraphBLAS.  Adding hierarchical matrices to all of GraphBLAS would be a huge amount of work.

**Comment by DrTimothyAldenDavis** [comment]
RedisGraph uses a related method:  it holds a matrix in 3 parts:  the primary matrix, a matrix with pending deletions, and a matrix with pending insertions.

**Comment by alexandergunnarson** [comment]
Thanks for the helpful clarifications!
