### ISSUE TITLE
option to only build static libs

### ISSUE THREAD

**Issue by Fabian188** [DrTimothyAldenDavis/SuiteSparse#227]
I suggest to add the option to compile only static libs.

I bundle suitesparse as static libs to our application and this would half the compile time for suitesparse.

I know it is quite some work as I tried to patch the code myself and failed. Also there are probably not that many use cases beside mine, but I thought I could kindly ask :)

Thanks, Fabian

**Comment by DrTimothyAldenDavis** [comment]
it would be quite a bit of work and it would likely break my demos or make it a lot harder to run them.  I'd prefer to keep the dynamic libraries intact.
