### ISSUE TITLE
cholmod and onemkl interaction linking issues

### ISSUE THREAD

**Issue by jakub-homola** [DrTimothyAldenDavis/SuiteSparse#229]
Hello,
I am having problems with cholmod and onemkl in the same project.

**Describe the bug**
When using cholmod and onemkl in the same project, linker (probably) links wrong functions. There is probably a conflict in function names, specifically with `dpotrf_`.

**To Reproduce**
Run the `demo.sh` script in [cholmod_vs_onemkl.zip](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/10298437/cholmod_vs_onemkl.zip) on the [intel devcloud](https://www.intel.com/content/www/us/en/developer/tools/devcloud/overview.html) (anyone can use the devcloud for development/testing).

What it does: there is a cpp file with a program that uses cholmod (very simple code). Compiling it and linking with cholmod works fine. But when I also link onemkl, it does not work, with the error message
```
Intel MKL ERROR: Parameter 4 was incorrect on entry to DPOTRF.
CHOLMOD warning: matrix not positive definite. file: /home/u180482/esp/tests/cholmod_vs_onemkl_2/SuiteSparse/CHOLMOD/Supernodal/t_cholmod_super_numeric.c line: 963

Intel MKL ERROR: Parameter 4 was incorrect on entry to DPOTRF.
./demo.sh: line 49: 27782 Segmentation fault      ./program_yesmkl.x
```
The error occurs in the `cholmod_factorize` function. I think the cause is the `dpotrf_` function it uses. Linker links `dpotrf_` from onemkl, but cholmod expects its own different `dpotrf_` with different signature and parameters.

This happens only for larger matrices, when supernodal is used. For smaller matrices it runs fine (replace `Kreg0.txt` with `Kreg0_small.txt` on line 57 in `source.cpp`).

**Expected behavior**
cholmod and oneMKL working side by side with no problem

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS (compute node on intel devcloud)
 - compiler: Intel(R) oneAPI DPC++/C++ Compiler 2023.0.0 (2023.0.0.20221201)
 - BLAS and LAPACK library: oneMKL, during cholmod make it reports this:
```
-- BLAS libraries:      /glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_gf_lp64.so;/glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_gnu_thread.so;/glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;-lpthread;-lm;-ldl
-- BLAS include:
-- BLAS linker flags:
-- LAPACK libraries:    /glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_gf_lp64.so;/glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_gnu_thread.so;/glob/development-tools/versions/oneapi/2023.0/oneapi/mkl/2023.0.0/lib/intel64/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
-- LAPACK include:
-- LAPACK linker flags:
```
 - Version: current stable branch, commit 648d6bd447ac93153da0c3d5e844f344c70c832c, readme says VERSION 6.0.1

**Additional context**
I understand this is probably not a cholmod bug, but rather a general issue with linking, but I have no idea what should I do. I need cholmod and onemkl work in the same project side by side. Any help would be appreciated.

Merry christmas.
Jakub

**Comment by DrTimothyAldenDavis** [comment]
It's a mismatch of the BLAS integer size.  When you compiled SuiteSparse_config, it was told to use the 64-bit BLAS. 

The Makefile in the zip folder has -lmkl_intel_ilp64 which means that a 64-bit BLAS is being used.  But from the cmake script, you have configured SuiteSparse_config with the 32-bit BLAS (see the mkl_gf_lp64).  The cmake configures the default BLAS integer in SuiteSparse_config.h.

You can't switch between 64-bit and 32-bit BLAS unless you override the settings in SuiteSparse_config.h with -DBLAS32 or -DBLAS64.  The Makefile needs -DBLAS32 I think.

**Comment by DrTimothyAldenDavis** [comment]
I would provide a more helpful error message than "not symmetric positive definite" but it's not possible.  There's no way to query the BLAS library to ask what it expects its integer size to be.

**Comment by jakub-homola** [comment]
Yes, thank you, the 32/64 bit integer mismatch was actually the issue here! I ended up compiling SuiteSparse_config and CHOLMOD using `CMAKE_OPTIONS="-DALLOW_64BIT_BLAS=true" make local`, forcing it to use 64-bit BLAS, and then in my Makefile linked it with the 64-bit BLAS. After that, the cmake reported `Looking for Intel 64-bit BLAS` and used the 64-bit version `mkl_gf_ilp64.so` instead of 32-bit `mkl_gf_lp64.so` (weird, that naming).

Thank you very much for help, I wouldn't be able to firuge it out on my own.

**Comment by DrTimothyAldenDavis** [comment]
Glad to help!
