### ISSUE TITLE
Make `dev` the default branch?

### ISSUE THREAD

**Issue by mmuetzel** [DrTimothyAldenDavis/SuiteSparse#261]
Given that caches can only be restored from the default branch and the fact that the CI will probably run much more often on the development branches, would it make sense to make `dev` the default branch of this repository?

Also, other big projects (like https://github.com/llvm/llvm-project) set their development branch as the default branch and have other branches for stable versions.

**Comment by DrTimothyAldenDavis** [comment]
That seems reasonable.  Let me think it over and make sure it doesn't break anything.

**Comment by mmuetzel** [comment]
See also #266 which enables populating the caches on the main branches again.

**Comment by DrTimothyAldenDavis** [comment]
So making dev the default branch will not have any effect on the caching?

**Comment by mmuetzel** [comment]
Making it the default branch would still be necessary to make the caches available for the CI in PRs.

It turns out that GitHub action caches can only be restored from the current branch or the default branch.
In PRs, the CI runs on a branch that GitHub creates specifically for the PR. On the first CI run in a PR, there won't be any caches for that branch. That means it would need to fall back to the caches from the default branch for the compiler cache to do its magic.
The compiler cache is most efficient if the changes between the last time it was updated and the current build are small. That means it makes sense to restore the compiler cache from either `dev2` or `dev`. Since you didn't want to have the CI run on `dev2`, that leaves `dev`. A cache from the `stable` branch would likely correspond to a code base which might be too different for the compiler cache to work efficiently.

For that to work, the caches on the default branch need to be actually populated (and preferably be pretty current). PR #266 activated populating the caches on the `dev` branch. It's still necessary to make `dev` the default branch though or the CI wouldn't pick up that cache in the CI.

Fwiw, the build time on the hosted runners without compiler cache is about 1 to 2.5 hours. With populated compiler cache, that build time reduces to 1 to 5 minutes.

**Comment by DrTimothyAldenDavis** [comment]
OK -- I can make dev the default branch. The stable branch is meant to be identical to the current stable release, so I'll keep that definition.  The dev branch is meant to be a working, tested branch with all pending and in-progress revisions for the next release.  And dev2 is my playground where things come and go, possibly broken at any given moment.

So making dev the default branch makes sense with the definitions of these 3 branches.

I see that llvm keeps a branch for each release, as well.  That's probably a good idea.

I might consider making a new branch for each stable release, so for example, I could have a release_v6.0.3 branch that would be the same as the v6.0.3 tag.  Current, stable is identical to the v6.0.3 release, as it should be.

That way, it might be easier to create a minor update, like v6.0.4, if I find a bug in v6.0.3, but have already moved on to a major update like v7.0.0.  I could just create a release_v6.0.4 branch from the existing (and read-only) release_v6.0.3.

**Comment by mmuetzel** [comment]
That sounds like a good plan to me.

Whether you'd like to maintain older versions in their dedicated branches is up to you. Afaict, usually only larger projects with many maintainers are doing that. Smaller or middle sized projects often just have a "stable" and a "development" branch (and maybe some "feature" branches). But that is up for your own decision and what are your goals and workflow.
Anyway, you could always branch from an older tag if that should become necessary to fix a bug in an old released version...

**Comment by DrTimothyAldenDavis** [comment]
That's true. I made a release_v6.0.3 branch which is locked and identical to v6.0.3. 

I will keep that one since v7.x is a "major" SO change (I had to do that because of a change to the user visible struct in SuiteSparse_config.c).
