### ISSUE TITLE
Inconsistent type in `cholmod_check_subset` declaration

### ISSUE THREAD

**Issue by CattleProdigy** [DrTimothyAldenDavis/SuiteSparse#268]
**Describe the bug**
In the implementation of `cholmod_{l_}check_subset`, the `Int` macro constant is used in the function signature for the `Set` parameter. This should generate  `int32_t*` or `int64_t*` depending the index type in use. However in `cholmod.h`, `cholmod_check_subset` has a plain `int*` for the `Set` parameter. `cholmod_l_check_subset` uses `int64_t*` as expected.

The existing code works but it's inconsistent with other methods (e.g. `print_subset`).

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/3fb9440657fd4671c08d8bf7be336538e9131f17/CHOLMOD/Include/cholmod.h#L2998

I suggest the following fix:
```patch
@@ -2995,7 +2995,7 @@ SUITESPARSE_PUBLIC
int cholmod_check_subset
(
    /* ---- input ---- */
-   int *Set,		/* Set [0:len-1] is a subset of 0:n-1.  Duplicates OK */
+   int32_t *Set,		/* Set [0:len-1] is a subset of 0:n-1.  Duplicates OK */
    int64_t len,        /* size of Set (an integer array) */
    size_t n,		/* 0:n-1 is valid range */
    /* --------------- */
```

**Additional context**
I'm writing bindings for CHOLMOD to call it from Rust. Consistent use of types makes automating this easier.

Thanks for having a look.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for catching the bug.  Yes, that should be an int32_t like the rest.  I also found a related inconsistency in the comments for cholmod_realloc_multiple in cholmod.h and fixed that tool.  I just revised it on the dev2 branch: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/249e3eec2757b126e11b9a790ba86b9ba7bd0ac9

**Comment by CattleProdigy** [comment]
You're welcome and thank you for the fix.
