### ISSUE TITLE
Error in installing Mongoose on MacOS

### ISSUE THREAD

**Issue by YiifeiWang** [DrTimothyAldenDavis/SuiteSparse#27]
I met an error in installing Mongoose. I fixed it as follows.

First, in /Mongoose/MATLAB/mongoose_make.m, line 53-54, it should be
`config_src = {
    '../../SuiteSparse_config/SuiteSparse_config' };`
instead of 
`config_src = {
    '../SuiteSparse_config/SuiteSparse_config' };`

Second, after I modify mongoose_make.m, another error occurs
`../Include/Mongoose_Internal.hpp:31:10: fatal error: 'SuiteSparse_config.h' file not found
#include "SuiteSparse_config.h"`

I copy /SuiteSparse_config/SuiteSparse_config.h to /Mongoose/Include/ and this error is solved. 

The setting of my laptop is as follows:
MacOS Catalina 10.15.3.
MATLAB Version 9.4.0.813654 (R2018a)
with 64-bit BLAS

This is a great software and it will be better if these errors can be removed.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for catching that.  I seem to have missed that when configuring the last release.  I've updated mongoose_make.m, which should fix this error.  Give it a try with the latest update I just posted.
