### ISSUE TITLE
Is `sparseinv` the best way to get diagonal of inverse of sparse SPD matrix?

### ISSUE THREAD

**Issue by alecjacobson** [DrTimothyAldenDavis/SuiteSparse#273]
The documentation of `sparseinv.m` writes:

```
% If
% A is symmetric and positive definite, then a Cholesky factorization is used
% (in which case P=Q' and L=U', and Z will include all diagonal entries of
% inv(A)).
```

I have a matrix `A` that is symmetric and positive definite (similar to the Laplacian of a 3D unstructured grid) and I would like to compute `d = diag(inv(A))`. Can I do better than `d = diag(sparseinv(A))` ? It seems like `sparseinv` is computing more than I need, but I'm unsure whether these values are necessary to compute the diagonal. 

Any hints?

**Comment by DrTimothyAldenDavis** [comment]
Yes, the sparse inverse method has to compute all the entries in the sparsity pattern of L.  It can't just compute the diagonal entries.

**Comment by alecjacobson** [comment]
Thanks! Good to know.
