### ISSUE TITLE
cannot install Suite Sparse 5.7.1 on my RHEL 7 machine

### ISSUE THREAD

**Issue by rrajasekpro** [DrTimothyAldenDavis/SuiteSparse#28]
**Describe the bug**
I am trying to install SuiteSparse 5.7.1 on my RHEL box

**To Reproduce**
1. download SuiteSparse-5.7.1.tar.gz
2. # tar zxvf SuiteSparse-5.7.1.tar.gz
3. cd SuiteSparse-5.7.1
4. make
....
[ 23%] Building CXX object CMakeFiles/mongoose_lib_dbg.dir/Source/Mongoose_QPNapDown.o
[ 24%] Building CXX object CMakeFiles/mongoose_lib_dbg.dir/Source/Mongoose_QPNapsack.o
[ 25%] Building CXX object CMakeFiles/mongoose_lib_dbg.dir/Source/Mongoose_QPNapUp.o
[ 25%] Building C object CMakeFiles/mongoose_lib_dbg.dir/External/mmio/Source/mmio.c.o
cc1: warning: command line option â-Woverloaded-virtualâ is valid for C++/ObjC++ but not for C [enabled by default]
[ 26%] Linking CXX static library lib/libmongoose_dbg.a
make[4]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
[ 26%] Built target mongoose_lib_dbg
make[4]: Entering directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
Scanning dependencies of target mongoose_unit_test_graph
make[4]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
make[4]: Entering directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
[ 27%] Building CXX object CMakeFiles/mongoose_unit_test_graph.dir/Tests/Mongoose_UnitTest_Graph_exe.o
[ 28%] Linking CXX executable tests/mongoose_unit_test_graph
lib/libmongoose_dbg.a(Mongoose_IO.o): In function `Mongoose::read_graph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:34: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
lib/libmongoose_dbg.a(Mongoose_IO.o): In function `Mongoose::read_matrix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char (&) [4])':
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:39: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
lib/libmongoose_dbg.a(Mongoose_IO.o): In function `Mongoose::read_matrix(char const*, char (&) [4])':
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:85: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:85: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:85: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/rrajasek/SuiteSparse-5.7.1/Mongoose/Source/Mongoose_IO.cpp:85: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
collect2: error: ld returned 1 exit status
make[4]: *** [tests/mongoose_unit_test_graph] Error 1
make[4]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
make[3]: *** [CMakeFiles/mongoose_unit_test_graph.dir/all] Error 2
make[3]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose/build'
/bin/sh: ./bin/demo: No such file or directory
make[1]: *** [default] **Error 127**
make[1]: Leaving directory `/home/rrajasek/SuiteSparse-5.7.1/Mongoose'
make: *** [go] **Error 2**

**Expected behavior**
clean install of SuiteSparse

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RHEL 7
 - compiler 
# gcc --version
gcc (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 - BLAS and LAPACK library, if applicable
Not sure about whether I need this or not

**Additional context**
I have verified with Dr Davis that my cmake works.

**Comment by DrTimothyAldenDavis** [comment]
This is a problem with your C++ library, not with SuiteSparse.

gcc 6.1.0 should be fine, as it fully supports C++11 (and 14 and most of 17). Also, the current version of Mongoose in SuiteSparse doesn’t even require C++11, so that shouldn’t be a show-stopper either way.

It seems to be a problem with different versions of GCC compiling different portions of the code, or an outdated version of libstdc++. Ultimately, a version mismatch in the toolchain. I would suggest trying:

yum upgrade libstdc++ 

or attempt to explicitly link with the version that comes with GCC 6.

**Comment by rrajasekpro** [comment]
Thank you. I will try that and let you know. But can you confirm the steps I took?

**Comment by DrTimothyAldenDavis** [comment]
The steps you used are fine.  It's your library setup for gcc and/or
libc++11 that is broken.
