### ISSUE TITLE
cuda libraries always being built

### ISSUE THREAD

**Issue by opoplawski** [DrTimothyAldenDavis/SuiteSparse#285]
**Describe the bug**
It seems like with 6.0.3 and 7.0.0 (as opposed to 6.0.1), some cuda libraries are always being built despite cuda support not being enabled.

**To Reproduce**
```
( cd build && cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF                    -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_INCLUDEDIR=/usr/include/suitesparse -DBLA_VENDOR=FlexiBLAS .. && cmake --build . -j4 )
...
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Looking for CUDA
-- CUDA: not found
-- CUDA: not enabled
...
-- Building SPQR_CUDA version: v3.0.3 (Jan 17, 2023)
...
-- Looking for CUDA
-- CUDA: not found
-- CUDA: not enabled
...
-- SPQR cuda:  spqr_cuda 
```
Looks like I get both spqr_cuda and cholmod_cuda.

**Expected behavior**
No _cuda libraries built.

**Desktop (please complete the following information):**
 - OS: Fedora rawhide

**Comment by DrTimothyAldenDavis** [comment]
The libraries are created as intentionally empty if cuda is not available. I found it simpler to construct them that way instead of deciding if I had to link against them or not.

**Comment by opoplawski** [comment]
I'm afraid that this may be challenging for distro packaging.  It's quite strange to ship something that isn't really functional, and I can't remove them since things are going to try to link to them.

**Comment by DrTimothyAldenDavis** [comment]
I have many places, like in test coverage, where I have to link against these libraries but it's not via a cmake script.  It's very hard to create the Makefiles to test if cuda is enabled or not. 

I would prefer to fold both libraries together so that libcholmod.so includes all the cuda functions but I couldn't get that to work in the cmake build system.

**Comment by DrTimothyAldenDavis** [comment]
If cuda is not enabled, then the libraries such as libcholmod.so don't depend on libcholmod_cuda.so.

**Comment by fxcoudert** [comment]
> If cuda is not enabled, then the libraries such as libcholmod.so don't depend on libcholmod_cuda.so

This is not true. `libspqr.so`definitely links against `libspqr_cuda.so`, we've seen it here in testing: https://github.com/JuliaLang/julia/pull/48855#issuecomment-1462362469

**Comment by DrTimothyAldenDavis** [comment]
I'll take a look.  Getting the CUDA to work with cmake was a real challenge.  Ideally, a single libcholmod.so would include any CUDA kernels, if CUDA is enabled, but I couldn't get that to work in cmake.  Then I had another problem on another side, where I use vanilla makefiles in my test coverage suites, and those were broken unless I took this route.

For production use, the library structure is more critical than for my internal test coverage tests (which are not part of the cmake build / test process ... yet).  I'll see if I can hack my internal test Makefiles to tolerate a better library structure.

**Comment by kiwifb** [comment]
I just got report on stuff like that in Gentoo. In fact, I am not so fussed about the existence of empty _cuda.so libraries in CHOLMOD and SPQR. It is a bit dirty but we can live with it. But one thing that happens is that the `NSTATIC` flag is not respected for _cuda libraries, _cuda.a libraries are shipped. Upon inspection in SPQR and I assume it is similar in CHOLMOD, there is duplication of the cmake installation code for cuda libraries in SPQR/CMakeList.txt and SPQR/SPQRGPU/CMakeList.txt and the later do not have code to respect NSTATIC.

**Comment by kiwifb** [comment]
I have a prototype patch for SPQR that respect NSTATIC for cuda, I will make a PR at the first opportunity.

**Comment by kiwifb** [comment]
It appears that particular NSTATIC issue is fixed in dev2, did I miss it as an important part of 7.0.1?

**Comment by DrTimothyAldenDavis** [comment]
Can you try out the v7.1.0.beta1 pre-release?  It has lots of updates to the cmake build system.

**Comment by kiwifb** [comment]
My last comment was a mistake. I was working in the evening after a long day and the stuff I found was something I put there :) - regarding the original request itself about installing _cuda.{so,a} libraries, I think that could be dealt simply by adding some `if ( SUITESPARSE_CUDA )` block around the installation part of `CMakeList.txt` in the gpu folder. I will give it a test once I can finish that `NSTATIC` work.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for all the feedback.  The NSTATIC is now in place in the v7.1.0 release. 

I'll give this another try.  I do understand that it's problematic.  I would like to skip at least the linking and installation of the *_cuda.so libraries if CUDA is not in use.  I just couldn't get that to work in the cmake scripts and the test scripts on my first try.

Stay tuned, and hopefully I can resolve this in v7.1.1 or perhaps v7.2.0 (which will add a version of SPQR with 32-bit integer indices for its sparse matrices).

**Comment by mmuetzel** [comment]
Maybe, installing pkg-config files could help downstream projects (that don't use CMake) to find out which libraries they need to link with.

We could have a look into how to create them automatically once the CMake overhaul gets close to a finish.

**Comment by mmuetzel** [comment]
See #356 for a PR that creates pkg-config files as part of the build process.
With that, it might be easier to find out whether or not to link to the *_cuda libraries.

@DrTimothyAldenDavis: Are those test scripts accessible somewhere?

**Comment by glaubitz** [comment]
> If cuda is not enabled, then the libraries such as libcholmod.so don't depend on libcholmod_cuda.so.

That doesn't seem to be the case for LoongArch and 64-bit SPARC on Debian where the build fails with:

```
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libcxsparse4/usr/lib/loongarch64-linux-gnu/libcxsparse.so.4.0.4 was not linked against libsuitesparseconfig.so.7 (it uses none of the library's symbols)
dpkg-shlibdeps: error: cannot find library libcholmod_cuda.so.4 needed by debian/libumfpack6/usr/lib/loongarch64-linux-gnu/libumfpack.so.6.1.1 (ELF format: 'elf64-loongarch' abi: '0201010200000003'; RPATH: '')
dpkg-shlibdeps: error: cannot find library libcholmod_cuda.so.4 needed by debian/libklu2/usr/lib/loongarch64-linux-gnu/libklu_cholmod.so.2.0.4 (ELF format: 'elf64-loongarch' abi: '0201010200000003'; RPATH: '')
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libamd3/usr/lib/loongarch64-linux-gnu/libamd.so.3.0.4 was not linked against libgfortran.so.5 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libamd3/usr/lib/loongarch64-linux-gnu/libamd.so.3.0.4 was not linked against libgcc_s.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: error: cannot find library libspqr_cuda.so.3 needed by debian/libspqr3/usr/lib/loongarch64-linux-gnu/libspqr.so.3.0.4 (ELF format: 'elf64-loongarch' abi: '0201010200000003'; RPATH: '')
dpkg-shlibdeps: error: cannot find library libcholmod_cuda.so.4 needed by debian/libklu2/usr/lib/loongarch64-linux-gnu/libklu.so.2.0.4 (ELF format: 'elf64-loongarch' abi: '0201010200000003'; RPATH: '')
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libbtf2/usr/lib/loongarch64-linux-gnu/libbtf.so.2.0.4 was not linked against libm.so.6 (it uses none of the library's symbols)
```

loong64: https://buildd.debian.org/status/fetch.php?pkg=suitesparse&arch=loong64&ver=1%3A7.1.0%2Bdfsg-3&stamp=1692910284&raw=0
sparc64: https://buildd.debian.org/status/fetch.php?pkg=suitesparse&arch=sparc64&ver=1%3A7.1.0%2Bdfsg-3&stamp=1692414038&raw=0

Does the build system have an architecture whitelist and doesn't know anything about loong64 and sparc64?

**Comment by DrTimothyAldenDavis** [comment]
I'll work on revising the build system so that the libcholmod_cuda.so library isn't built at all when CUDA is not enabled.

**Comment by mmuetzel** [comment]
I have a changeset to skip building libcholmod_cuda if configuring without `-DENABLE_CUDA=ON` almost ready.
But it's getting late. I'll try to open a PR tomorrow.

**Comment by mmuetzel** [comment]
I guess this can be closed now that #369 and #374 are merged.

**Comment by DrTimothyAldenDavis** [comment]
Yes, I'm testing it now on my various platforms.  Looking good.  The SPQR and CHOLMOD cmake correctly builds SPQR_CUDA and CHOLMOD_CUDA on my desktop (with GPUs and CUDA) but not on my Mac (without a CUDA-based GPU).

My top-level Makefile on my Mac still builds the SuiteSparse_GPURuntime and GPUQREngine libraries, but they aren't linked from CHOLMOD or SPQR.  The corresponding *.dylib and *.a files are empty.  It would be nice to skip those but that's not so critical.  A linux distro or Mac homebrew maintainer would likely not use my top-level Makefile anyway, and they could just skip the "cd GPUQREngine/build ; cmake .. ; cmake --build ." step themselves, if CUDA is not enabled for their build.

The top-level Makefile might go away at some point anyway, to eventually be replaced with a top-level CMakeLists.txt file.  Then it would be easier to skip the build of SuiteSparse_GPURuntime and GPUQREngine.

This test was done on my M1 MacBook Air.  I will repeat the tests on my Dell Linux laptop and my Intel-based MacBook Pro.

But so far it's looking like this issue is resolved.

Thanks!

**Comment by opoplawski** [comment]
Fedora package builds are looking good.  Thank you for working on this!

**Comment by DrTimothyAldenDavis** [comment]
Great!  Thanks for trying it out.  I will post SuiteSparse v7.2.0.beta1 shortly.
