### ISSUE TITLE
SuiteSparse sparse matrices vs. gSmart's (2021) implementation?

### ISSUE THREAD

**Issue by alexandergunnarson** [DrTimothyAldenDavis/SuiteSparse#292]
**Is your feature request related to a problem? Please describe.**
No problem here; just a curiosity.

**Describe the solution you'd like**
I'm curious how SuiteSparse compares to [gSmart (2021)](https://arxiv.org/pdf/2106.14038.pdf)'s custom sparse matrix implementation. I'm assuming SuiteSparse has the superior implementation, since it's ostensibly had a lot more attention and thought given to it, as well as real-world usage, as opposed to something purpose-built for a research paper.

**Describe alternatives you've considered**
N/A

**Additional context**
From what I can gather, gSmart reported [MAGiQ (2019)](https://repository.kaust.edu.sa/bitstream/handle/10754/631280/FuadJamourThesis.pdf?sequence=3&isAllowed=y)'s benchmarks of WatDiv-100M, which were run on a comparatively old (and single-threaded!) version of SuiteSparse. It's to be expected, then, that gSmart reports orders of magnitude better performance. But I am curious whether there are any hidden gems in the "Light-weight Sparse Matrix (LSpM) RDF Storage" that gSmart introduces, or whether they take an approach that SuiteSparse now makes obsolete.

**Comment by DrTimothyAldenDavis** [comment]
No idea how they would compare.  The thesis dates to Feb 2019, which may have used v2.2.3 (released Dec 2018).  The thesis doesn't say what version was used so it's likely even older than that.  That is a very early version of GraphBLAS..  It wasn't meant to be fast, even single-threaded, although I had started doing a few performance optimizations by then.  It was just a version that mainly illustrated the idea of GraphBLAS and got the API to work.

**Comment by alexandergunnarson** [comment]
Totally makes sense! Thanks for the input.
