### ISSUE TITLE
CMake Error at cmake/FindSuiteSparse

### ISSUE THREAD

**Issue by mgrallos** [DrTimothyAldenDavis/SuiteSparse#303]
Hi I was trying to build openvslam which needs SuiteSparse and I had these errors 

![image](https://user-images.githubusercontent.com/64775540/220809336-ca069469-9e1b-41ae-828a-adb755df8b36.png)

I have no idea what causes this.

**Comment by mmuetzel** [comment]
IIUC, that file isn't installed by SuiteSparse, but it is part of the build system of openvslam. Please, consider reporting this issue to the developers of openvslam.

**Comment by DrTimothyAldenDavis** [comment]
Correct, that's not my file.
