### ISSUE TITLE
Are there plans to make Rust bindings?

### ISSUE THREAD

**Issue by jgsimard** [DrTimothyAldenDavis/SuiteSparse#310]
Hi,
Are there plans to make official Rust bindings?
Thanks

**Comment by DrTimothyAldenDavis** [comment]
I don't have any plans to do so.

**Comment by jgsimard** [comment]
Thanks for the information

**Comment by DrTimothyAldenDavis** [comment]
Cool!  I'll add a link to it

**Comment by DrTimothyAldenDavis** [comment]
(Reopening to remind me to add a link): https://github.com/cpmech/russell

**Comment by DrTimothyAldenDavis** [comment]
Link added to README.md (currently in dev2 branch).
