### ISSUE TITLE
MPFR locating

### ISSUE THREAD

**Issue by VictorEijkhout** [DrTimothyAldenDavis/SuiteSparse#320]
I get the following error:

```
-- major/minor/patch: #define MPFR_VERSION_STRING "3.1.1"
CMake Error at /opt/apps/cmake/3.26.3/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPFR: Found unsuitable version "3.1.1", but required is at
  least "4.0.2" (found /usr/lib64/libmpfr.so.4.1.1)
Call Stack (most recent call first):
  /opt/apps/cmake/3.26.3/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindMPFR.cmake:96 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)
```

Even though:

```
[staff suitesparse:186] echo $PKG_CONFIG_PATH
/work2/00434/eijkhout/mpfr/installation-4.2.0-skx-intel22/lib/pkgconfig:/scratch/projects/compilers/oneapi_2022.3.0/mkl/latest/tools/pkgconfig
[staff suitesparse:187] ls /work2/00434/eijkhout/mpfr/installation-4.2.0-skx-intel22/lib/pkgconfig
mpfr.pc
```

Why is this not found? Should I set environment variables instead? I can not find the list of settable CMake variables for SuiteSparse. Link please?

**Comment by mmuetzel** [comment]
It looks like the detected headers don't match the library.
Do you have multiple versions of MPFR installed? If you do, try pointing `CMAKE_PREFIX_PATH` to the prefix of the installation you'd like to use.

**Comment by VictorEijkhout** [comment]
Correct me if I'm wrong. The `CMAKE_PREFIX_PATH` is where `.cmake` files are found. MPFR does not come with those.

**Comment by mmuetzel** [comment]
`CMAKE_PREFIX_PATH` is a list of the prefixes where packages are installed to (with, e.g., `bin`, `lib`, `include` folders) that cmake should scan.
You might be thinking of `CMAKE_MODULE_PATH`?
https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html
https://cmake.org/cmake/help/latest/variable/CMAKE_MODULE_PATH.html

**Comment by VictorEijkhout** [comment]
Got it. And that seems to have solved it. Thanks.

**Comment by e-eight** [comment]
Sorry to revive this again. 

I am having this same issue with the latest version of SuiteSparse. `pkg-config` detects the correct path, but SuiteSparse does not seem to use that. I tried pointing `CMAKE_LIBRARY_PATH` to the location of the `mpfr` library (`export CMAKE_LIBRARY_PATH=/opt/ohpc/pub/apps/mpfr/4.2.1/lib:$CMAKE_LIBRARY_PATH`). This did not work.

**Comment by mmuetzel** [comment]
> Sorry to revive this again. 
> 
> I am having this same issue with the latest version of SuiteSparse. `pkg-config` detects the correct path, but SuiteSparse does not seem to use that. I tried pointing `CMAKE_LIBRARY_PATH` to the location of the `mpfr` library (`export CMAKE_LIBRARY_PATH=/opt/ohpc/pub/apps/mpfr/4.2.1/lib:$CMAKE_LIBRARY_PATH`). This did not work. 

CMake needs to know where the libraries *and* headers are installed.
Did you try setting `CMAKE_PREFIX_PATH` instead?

**Comment by e-eight** [comment]
Thanks! That bit is working now. Having other problems, but will create a different issue for that.

**Comment by VictorEijkhout** [comment]
Re-reviving this.
```
[staff suitesparse:663] echo $CMAKE_PREFIX_PATH
/work2/00434/eijkhout/mpfr/installation-mpfr-4.2.1-clx-intel23.1:more......
```
and 
```
[staff suitesparse:665] ls /work2/00434/eijkhout/mpfr/installation-mpfr-4.2.1-clx-intel23.1
include/  lib/  share/
```

but suitesparse still reports
```
-- gmp static:  /usr/lib64/libgmp.so
-- from mpfr.h file: #define MPFR_VERSION_STRING "3.1.1"
CMake Error at /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPFR: Found unsuitable version "3.1.1", but required is at
  least "4.0.2" (found /usr/lib64/libmpfr.so.4.1.1)
Call Stack (most recent call first):
  /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindMPFR.cmake:91 (find_package_handle_standard_args)
  CMakeLists.txt:97 (find_package)
```

This is the latest 7.8.3 release
