### ISSUE TITLE
Files not cleant by "make purge"

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#322]
In the process of packaging SuiteSparse 7.0.1 for Debian, I found that some generated files are not properly cleant by `make purge`:

- `Mongoose/Lib` (I guess this file should not be generated, probably a bug in `Mongoose/CMakeLists.txt`)
- `Mongoose/Doc/Mongoose_UserGuide.{aux,bbl,blg,log,out,toc}` (there are some provisions in `Mongoose/CMakeLists.txt` for cleaning these files, but they don’t get executed by `make purge`)
- `RBio/temp.rb` (file generated by the demo)

**Comment by DrTimothyAldenDavis** [comment]
Thanks -- I'll update the make target to do that.

**Comment by DrTimothyAldenDavis** [comment]
This is now fixed in the dev2 branch, and I hope to release v7.1.0 tomorrow (June 12).  Thanks for the feedback.
