### ISSUE TITLE
Inconsistent build flags for Mongoose

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#323]
The CMake file for Mongoose (`Mongoose/CMakeLists.txt`) manipulates build flags in a way that is inconsistent with other libraries:
- it compiles the static library with position independent code (PIC), see line 181
- it adds `-O3` and various other flags to `CXXFLAGS`, see lines 314-351

For consistency with other SuiteSparse libraries, it would be better to remove these lines. I also had to remove them for the Debian packaging, because they don’t play well with distro packaging policies.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback.  Yes -- those settings should be consistent.  I'll take a look.

**Comment by DrTimothyAldenDavis** [comment]
This is now fixed in the dev2 branch.
