### ISSUE TITLE
Can you provide the cmake build support?

### ISSUE THREAD

**Issue by jiapei100** [DrTimothyAldenDavis/SuiteSparse#324]
something very similar to https://github.com/sergiud/SuiteSparse ?

Cheers

**Comment by DrTimothyAldenDavis** [comment]
It’s in progress, in the dev branch

**Comment by jiapei100** [comment]
@DrTimothyAldenDavis 
Not there yet right? I cannot see **CMakeLists.txt** from my side in **dev** branch.
So, when will you plan to have it released? 

Thank you

**Comment by DrTimothyAldenDavis** [comment]
Dev2 branch and pull requests there.

**Comment by DrTimothyAldenDavis** [comment]
It's also under discussion in two issues (in progress):  https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/309 and https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/175 so I'll close this issue #324 as a duplicate.
