### ISSUE TITLE
 Performing Test TEST_FOR_SSIZE_T - Failed

### ISSUE THREAD

**Issue by ASLabadi** [DrTimothyAldenDavis/SuiteSparse#329]
Hi Guys, 
I installed CHOLMOD (CUDA disabled), and I was able to work on it perfectly.

Now I want to compile CHOLMOD with CUDA enabled. However, since last week I am trying to build CHOLMOD, but I am having weird errors.

<steps i did>
1- I downloaded the stable version and started from scratch
and enabled cuda from the first package (suite sparse config)
2- all of cmake generation, build , and installation are successful for (  suite sparse config, AMD, CAMD, COLAMD, and CCOLAMD)
3- CHOLMOD is failing during the build command

 <My system :>
I have visual studio 2022, working on Windows.
I have CUDA toolkit 12.1, and it works perfectly. I tested it on a Cuda sample.
And I have BLAS and Lapack from both Intel one API and also from this website (https://www.netlib.org/lapack/), and I tried both the Intel and the open-source ones.

<The issue>
When creating cmake files for the CHOLMOD project - CUDA On
the cmake generates the build files perfectly 
only one strange observation is :
-- Performing Test TEST_FOR_SSIZE_T
-- Performing Test TEST_FOR_SSIZE_T - Failed
-- #include <sys/types.h> and ssize_t: not found
the full log is attached with the post.
when type the command: cmake --build .  
i get a lot of errors mostly related to the linker or syntax errors such as :

1-
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\GPU\cholmod_cuda.vcxproj]
cholmod_l_gpu.obj : error LNK2019: unresolved external symbol SuiteSparse_time referenced in function cholmod_l_gpu_memorysize [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\GPU\cholmod_cud
a.vcxproj]
cholmod_l_gpu.obj : error LNK2019: unresolved external symbol cholmod_l_error referenced in function cholmod_l_gpu_deallocate [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\GPU\cholmod_cuda
.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\GPU\Debug\cholmod_cuda.dll : fatal error LNK1120: 2 unresolved externals [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\GPU\cholmod_cu
da.vcxproj]

2-
 C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(55,9): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type [C:\SuiteSparse-st
able\SuiteSparse-stable\CHOLMOD\build\cholmod_static.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(120,63): error C2036: 'void *': unknown size [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\cholmod_static
.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(121,61): error C2036: 'void *': unknown size [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\cholmod_static
.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(122,64): error C2036: 'void *': unknown size [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\cholmod_static
.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(123,64): error C2036: 'void *': unknown size [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\cholmod_static
.vcxproj]
C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(124,62): error C2036: 'void *': unknown size [C:\SuiteSparse-stable\SuiteSparse-stable\CHOLMOD\build\cholmod_static

I will attach the output of the building process.
I am sorry for the long post and wish if someone can help me.

[cmake generation log.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/11725977/cmake.generation.log.txt)
[building log.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/11725981/building.log.txt)

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback.  I haven't ever been able to get CUDA working on Windows, and I won't be able to.  I could fix this particular issue but I'm sure there would be more.  CUDA development on Windows is just too difficult.  In particular, the memory management we use in GraphBLAS for CUDA just doesn't work at all on Windows.  So I don't have any plans to support CUDA on Windows.

You're correct that `sizeof(void *)` is not something that is portable to Windows, so it's something I avoid when dealing with code that is to be ported to all platforms (Linux, Mac, Windows).  It's not required be equal to 1, in particular.  It's not defined in the ANSI C11 spec.  It does work on Linux & Mac, but I've seen this come up in some compilers on Windows.
