### ISSUE TITLE
Ubuntu: sudo apt install libsuitesparse-dev instead of installing from source

### ISSUE THREAD

**Issue by nordfalk** [DrTimothyAldenDavis/SuiteSparse#33]
Please add a note that Ubuntu users can just write

` sudo apt install libsuitesparse-dev`

No need of installing from source

**Comment by tkircher** [comment]
Unless you're using a system based on bionic that can't be upgraded and you need a newer version of suitesparse.

**Comment by gaotao19890725** [comment]
when I "sudo apt install libsuitesparse-dev" and then run the project ElasticFusion, the error occurs: can not find SuiteSparse, can you give me some suggestion. thank you.

**Comment by DrTimothyAldenDavis** [comment]
I don't manage the "libsuitesparse-dev" packages for any linux distro.  You
need to check with the linux distro maintainers.
