### ISSUE TITLE
[CCOLAMD] Variable `cs` set but not used

### ISSUE THREAD

**Issue by acxz** [DrTimothyAldenDavis/SuiteSparse#38]
**Describe the bug**
```
CCOLAMD/Source/ccolamd.c:1563:9: warning: variable ‘cs’ set but not used [-Wunused-but-set-variable]
1563 |     Int cs ;
     |         ^~                                       
```

**To Reproduce**
Steps to reproduce the behavior.

git clone
cd CCOLAMD
make

**Expected behavior**

No warnings

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - compiler: gcc 9.3.0
 - BLAS and LAPACK library, if applicable N/A
 - CCOLAMD Version: latest from master

**Additional context**

N/A

**Comment by DrTimothyAldenDavis** [comment]
This is not a bug, but intentional.  The variable 'cs' is used when debug mode is enabled.
