### ISSUE TITLE
[Feature request] KLU: allow specifying which nonzero values changed to further reduce cost of refactor

### ISSUE THREAD

**Issue by timothyschoen** [DrTimothyAldenDavis/SuiteSparse#384]
Hi! I'm working on a circuit simulator for the pure-data audio patching environment, and I've successfully been using KLU for this. The performance is so good, and it's also pretty realtime friendly, so thanks for you work on this!

The problem I'm facing, is that my circuit simulation system requires iteration for transistors and diodes. During these iterations, I have to call refactor and solve, since both my A and B matrix changes. The changes to the A matrix are however, very small. I wonder if there would be a way to further reduce the cost of klu_refactor, if we know only a few values have changed? Perhaps there could be a function called klu_partial_refactor, that takes in an extra argument to specify which values have changed?

Thanks again for your work. I'm no mathematician, so excuse me of my use of terminology isn't completely correct, or if this is completely impossible.

<img width="374" alt="Screenshot 2023-09-07 at 14 38 43" src="https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/44585538/31a4c44c-63e7-4736-bed2-c8cd6c318734">

**Comment by DrTimothyAldenDavis** [comment]
It's not entirely impossible, but very difficult in general.  I do have several update/downdate methods that can revise a factorization after a low-rank change, but most are for Cholesky, not LU.  I have an LU update/downdate but it's for the SPEX package, which solves exact systems of equations (and thus is too costly for your usage).

There are limitations in how the updates can be described, as well.  It's not easy to take in an arbitrary list of values that have changed.  For Cholesky, for example, the update is `A = A + w*w'` where w is an n-by-k sparse matrix; this is called a "rank k" change (assuming all columns of w are linearly independent).  The downdate is `A=A-w*w'`.

**Comment by timothyschoen** [comment]
Thanks for your quick response, I figured it wouldn't be that simple.
