### ISSUE TITLE
pkgconfig files still require CUDA libraries

### ISSUE THREAD

**Issue by opoplawski** [DrTimothyAldenDavis/SuiteSparse#392]
**Describe the bug**
Building Fedora without CUDA, we are still ending up with CUDA dependencies in some pkgconfig files:
```
./usr/lib64/pkgconfig/KLU_CHOLMOD.pc:Requires.private: KLU BTF CHOLMOD CHOLMOD_CUDA
./usr/lib64/pkgconfig/UMFPACK.pc:Requires.private: SuiteSparse_config AMD  CHOLMOD CHOLMOD_CUDA
```
In Fedora this generates an unsastifiable dependency on `pkgconfig(CHOMOD_CUDA)`.

**Expected behavior**
No CHOLMOD_CUDA entries in the .pc files.

**Comment by mmuetzel** [comment]
Thanks for reporting.
I'll try to have a look at it soon.

**Comment by mmuetzel** [comment]
I opened #393 which should fix this.

**Comment by opoplawski** [comment]
Looks good to me, thanks!
