### ISSUE TITLE
Mangoose doesn't link with DNSTATIC=1

### ISSUE THREAD

**Issue by antonio-rojas** [DrTimothyAldenDavis/SuiteSparse#406]
**Describe the bug**
Mangoose fails to link when building suitesparse with DNSTATIC=1
```
/usr/bin/ld: libmongoose.so.3.2.0: undefined reference to symbol 'SuiteSparse_time'
/usr/bin/ld: /build/suitesparse/src/SuiteSparse-7.2.0/SuiteSparse_config/build/libsuitesparseconfig.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**To Reproduce**
```
CMAKE_OPTIONS=" -DNSTATIC=ON" \
  make
```

**Expected behavior**
Builds.
Changing `PRIVATE` to `PUBLIC` in https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/Mongoose/CMakeLists.txt#L212 fixes it.

**Desktop (please complete the following information):**
 - OS: Linux x86_64
 - compiler gcc 13.2.1
 - BLAS and LAPACK library, if applicable
 - Version 7.2.0

**Additional context**

**Comment by mmuetzel** [comment]
Thanks for reporting the issue.

See #407 for a possible fix.

While the change that you proposed also avoids the dependency issue for the affected tests and demos, it would lead to overlinking of projects that don't use functions from SuiteSparse_Config.

**Comment by DrTimothyAldenDavis** [comment]
I merged it in but I guess the problem got closed automatically as a result.  Let me reopen, and then I'll close it if we're sure it fixes the problem.

**Comment by antonio-rojas** [comment]
I confirm that the commit fixes the build for me.
