### ISSUE TITLE
install_name_tool missing in a few Makefiles

### ISSUE THREAD

**Issue by hespanha** [DrTimothyAldenDavis/SuiteSparse#42]
**Describe the bug**
Calls to install_name_tool is needed when moving dynamic libraries around in OSX. These calls are missing in the "install" sections of several of the Makefiles:
	AMD/Lib/Makefile
	CAMD/Lib/Makefile
	CCOLAMD/Lib/Makefile
	CHOLMOD/Lib/Makefile
	COLAMD/Lib/Makefile
	SuiteSparse_config/Makefile
	UMFPACK/Lib/Makefile

**To Reproduce**
'make install' and link libraries under OSX. The executables will not be able to find the dynamic libraries.

**Desktop (please complete the following information):**
OSX

I fixed this in my copy and can make a pull request.

**Comment by DrTimothyAldenDavis** [comment]
This should now be fixed, since I'm using CMake exclusively in the (beta) SuiteSparse v6.0.0.
