### ISSUE TITLE
`make ..` after `cmake ..` is not working for me

### ISSUE THREAD

**Issue by enjoysmath** [DrTimothyAldenDavis/SuiteSparse#43]
**Describe the bug**
Make is not doing the proper thing according to the library build instructions on the github readme.

**To Reproduce**
1. Download the latest SuiteSparse-5.7.2.zip.
2. Open up a standard windows command prompt, already having Cmake installed and MSYS's make installed using `pacman -S make` and adding `C:\msys64\usr\bin` to your Path env variable.
3. cd to SuiteSparse/GraphBLAS/build
4. Try copy / pasting : `cd GraphBLAS/build ; cmake .. ; make ; cd ../Demo ; ./demo`
and running.  Complains about directory not found.
5. Try breaking up the command, do:
`cmake ..` (appears to work)
`make ..`  (fails)
6. The last part fails and here is a detail of the total command line interaction:
```
> cmake ..
-- CMake version: 3.17.0-rc1
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Building dynamic GraphBLAS library only
-- CMAKE build type:          Release
-- CMAKE C Flags release:     /MD /O2 /Ob2 /DNDEBUG
-- CMAKE compiler ID:         MSVC
-- CMAKE thread library:
-- CMAKE have pthreads:
-- CMAKE have Win32 pthreads: 1
-- CMAKE have OpenMP:         TRUE
-- Automatic selection of synchronization method for user threads
-- Using OpenMP to synchronize user threads
-- Using OpenMP for internal parallelism
-- CMAKE C flags: /DWIN32 /D_WINDOWS /W3 /O2 -wd"4244" -wd"4146" -wd"4018" -wd"4996" -wd"4047" -wd"4554" /MD /O2 /Ob2 /DNDEBUG -openmp -DUSER_OPENMP_THREADS  -openmp -DHAVE_WINDOWS_THREADS
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/FruitfulApproach/Desktop/HutterPrizeSubmission/SuiteSparse-5.7.2/GraphBLAS/build

> make ..
make: Nothing to be done for '..'.
```

**Expected behavior**
For the build to go through.

**Screenshots**
![image](https://user-images.githubusercontent.com/1606391/83812505-866c1680-a670-11ea-9924-76b713c9138a.png)

**Desktop:**
 - OS: Windows 10 Home
 - compiler: Whichever would be used by compiling with latest MSYS (dowloaded today)
 - Version: downloaded today, SuiteSparse 5.7.2

**Additional context**
I tried doing this in MSYS's provided bash shell and the same exact error occurs, namely:
`make: Nothing to be done for '..'.`

**Comment by DrTimothyAldenDavis** [comment]
In the build directory,  you need just "make" not "make ..".

**Comment by enjoysmath** [comment]
@DrTimothyAldenDavis 

Tried that, which results in:
```> make
make: *** No targets specified and no makefile found.  Stop.```

**Comment by DrTimothyAldenDavis** [comment]
What is in the "build" folder?  "cmake .." should create a Makefile there.

On windows, all I've tested is the import of the CMake script into a MS Visual Studio project.  Then I build it in MS Visual Studio.  That process works fine.

**Comment by enjoysmath** [comment]
How do you do that method?
