### ISSUE TITLE
single precision sparse matrices are in progress for CHOLMOD, UMFPACK, and SPQR

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [DrTimothyAldenDavis/SuiteSparse#447]
See the discussion here: https://github.com/DrTimothyAldenDavis/SuiteSparse/discussions/446 .

**Comment by DrTimothyAldenDavis** [comment]
CHOLMOD 5.0.0 supports basic operations now on single precision sparse matrices, with SuiteSparse 7.3.0.beta1 (just released).

**Comment by syby119** [comment]
Cool.

**Comment by DrTimothyAldenDavis** [comment]
CHOLMOD 5.1.0 is now written, essentially fully polished, and almost ready to release in SuiteSparse 7.4.  It appears in the default dev branch.  It has a full implementation of single precision sparse matrices.

UMFPACK and SPQR are next (I haven't started those two packages yet).

**Comment by DrTimothyAldenDavis** [comment]
CHOLMOD 5.1.0 is now ready in SuiteSparse 7.4.0, in the default dev branch of the SuiteSparse repo.  I'll release a 7.4.0.beta1 soon.

UMFPACK and SPQR are not yet revised to handle single precisions matrices, so this issue will remain open until then.

**Comment by DrTimothyAldenDavis** [comment]
I'll close this as an issue -- it's better done as a Discussion thread, I think.

SuiteSparse 7.4.0.beta1 has just been released, with CHOLMOD 5.1.0, which now supports single precision real and complex matrices.  UMFPACK and SPQR are next, and perhaps other solvers (CXSparse, KLU, LDL, ...).
