### ISSUE TITLE
Are low-rank updates for sparse Cholesky factorizations possible from MATLAB API?

### ISSUE THREAD

**Issue by alecjacobson** [DrTimothyAldenDavis/SuiteSparse#47]
(Thank you for this great library and making it so easy to install)

I understand that the built-in `cholupdate` in MATLAB only supports *dense* positive definite matrices. I'd like to do this with a sparse matrix. I've installed SuiteSparse's MATLAB tools via `SuiteSparse_install`, but I can't find in the API whether such up-/down-dates are exposed. (The `cholupdate` still points to MATLAB's built in dense one).

The `SuiteSparse/MATLAB_Tools/Factorize/Demo/factorize_demo.m` uses `chol_update` but it appears to be the MATLAB built in dense one, too.

Are low-rank updates for sparse Cholesky factorizations possible from the MATLAB API?

If not, are low-rank updates for sparse Cholesky factorizations possible from the C/C++ API?

I see that there's a `ldlupdate`, should I being using this instead of `chol`? If so, should I expect a performance hit switching from `ldl` factorization to `chol`?

**Comment by DrTimothyAldenDavis** [comment]
The low rank update/downdate methods are available in both MATLAB and C.

For MATLAB: see ldlupdate.m, and examples in cholmod_updown_demo.c, in the
CHOLMOD/MATLAB folder.  I think the MATLAB interface ldlchol uses my
supernodal factorization and then converts it to simplicial on output, if I
recall correctly.  So there should be no loss of performance as compared to
the built-in chol.

For C: it's described in the user guide.  All the update/downdate methods
are available there.

**Comment by alecjacobson** [comment]
perfect. thank you.
