### ISSUE TITLE
CHOLMOD 5.0.0's header clashes with <complex.h>

### ISSUE THREAD

**Issue by UncombedCoconut** [DrTimothyAldenDavis/SuiteSparse#478]
This is not a bug, per se, but rather a bad interaction which may have been overlooked.
Suppose for some reason you've `#include`d `<complex.h>` -- directly or otherwise -- and later `<cholmod.h>`.
Then, under SuiteSparse 7.3.0 / CHOLMOD 5.0.0, you're dead because this declaration clashes with the `I` macro for the imaginary unit:
```C
int cholmod_realloc_multiple    // returns true if successful, false otherwise
(
    size_t nnew,    // # of items in newly reallocate memory
    int nint,       // 0: do not allocate I or J, 1: just I, 2: both I and J
    int xdtype,     // xtype + dtype of the matrix:
                    // (CHOLMOD_DOUBLE, _SINGLE) +
                    // (CHOLMOD_PATTERN, _REAL, _COMPLEX, or _ZOMPLEX)
    // input/output:
    void **I,       // integer block of memory (int32_t or int64_t)
    void **J,       // integer block of memory (int32_t or int64_t)
    void **X,       // real or complex, double or single, block
    void **Z,       // zomplex only: double or single block
    size_t *n,      // current size of I, J, X, and/or Z blocks on input,
                    // changed to nnew on output, if successful
    cholmod_common *Common
) ;
```

In your opinion, is it worth tweaking this declaration to avoid this problem? (I'll live if the answer is no.)
Thanks!

(Reproducer: with GCC 13 or Clang 16, run `cc -c` on a file with statements `#include <complex.h>` and `#include <cholmod.h>`. There's a compile error on the included `void **I,` line.)

**Comment by mmuetzel** [comment]
Thanks for your report.
CHOLMOD should probably avoid to repurpose symbols that could be defined by including a standard header. Just renaming `I` in the header would probably be fine.

**Comment by DrTimothyAldenDavis** [comment]
Oops.  In my opinion, C11 adding a single letter macro "I" was a really bad mistake, but I can't fix that ...

I'll fix it shortly and release a CHOLMOD 5.0.1 and SuiteSparse 7.3.1.

**Comment by UncombedCoconut** [comment]
Thank you! Yes, I agree with that assessment. :)

**Comment by DrTimothyAldenDavis** [comment]
I've posted a SuiteSparse 7.3.1.beta1 with this fix:  https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.3.1.beta1

Can you give it a try?

**Comment by UncombedCoconut** [comment]
> I've posted a SuiteSparse 7.3.1.beta1 with this fix: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.3.1.beta1
> 
> Can you give it a try?

Thanks, works perfectly for me.

**Comment by DrTimothyAldenDavis** [comment]
Great!
