### ISSUE TITLE
The original order of matrix L needs to be restored

### ISSUE THREAD

**Issue by Aries-Wu** [DrTimothyAldenDavis/SuiteSparse#488]
I need to get the lower triangular matrix L in A=LL' and can only use CHOLMOD_NATRUAL to ensure that the order is not broken. When the dimension exceeds 1 million, CHOLMOD errors are too large and take too long. At first I thought about using other methods to get PAP' = LL', and turn into A = P'LL'P = (P'LP) (P'L'P) = (P'LP) (P'LP)', but (P'LP) is not a lower triangular matrix. So is there a quick way to factorize and keep the original order?

**Comment by DrTimothyAldenDavis** [comment]
No it's not possible in any factorization. Not just in cholmod. No sparse or dense factorization can do this.

**Comment by Aries-Wu** [comment]
Thank you! Yes, I agree with that assessment. :)
