### ISSUE TITLE
Inconsistency in documentation cleaning rules

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#502]
Since commit eb2fae31610e2495c59f1e1b107ef5db6b52c1a2, `CHOLMOD/Doc/Makefile` no longer cleans the generated `_*.tex` files after building the PDF documentation.

This is not consistent with what is done with other PDF throughout SuiteSparse. Moreover, running  `make clean` from the top-level directory does not clean those files, because `make clean` is never called recursively in documentation folders.

Please either revert this change, or modify `make clean` so that it also runs recursively in documentation folders.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for catching this.  I was debugging the creation of the *tex files and neglected to put this back in.  I've reverted the change and it will appear in the next release.

**Comment by DrTimothyAldenDavis** [comment]
Thanks again for catching this. This is now fixed in SuiteSparse 7.4.0, in the default dev branch of the SuiteSparse repo.  I'll release a 7.4.0.beta1 soon.
