### ISSUE TITLE
Access row/column/value pointers in cholmod_factor* L

### ISSUE THREAD

**Issue by ruizhi92** [DrTimothyAldenDavis/SuiteSparse#512]
I have some legacy code that depends on choldmod version 2.0.1 (in suitesparse-4.0.2). In the legacy code, cholesky factorization is preformed on a sparse matrix A given in the format of row/column/value pointers. The factorization result L is used to select a submatrix from L afterwards. Usage was like:
```
// factorization
cholmod_common c;
cholmod_start(&c);
c.final_asis = false;
c.final_ll = true;
c.final_super = false;
c.postorder = false;
cholmod_sparse* A = cholmod_allocate_sparse(n, n, Ap[n], 1, 1, -1, CHOLMOD_REAL, &c);  // n and Ap are given
A->p = Ap;
A->i = Ai;  // Ai is given
A->x = Ax;  // Ax is given
cholmod_factor* L = cholmod_analyze(A, &c);
cholmod_factorize(A, L, &c);

// select submatrix
int* Lp = (int*) L->p;
int* Lx = (int*) L->x;
double* Lx = (double*) L-x;
for (int i = 0; i < 3; i++) {  // column range 0:3 and row range 1:4 as an example
  for (int j = Lp[i]; j < Lp[i+1]; j++) {
    if (Li[j] >= 1 && Li[j] < 4) {
      // put the element in the submatrix
    }
  }
}
```

The code works fine with the old version. Now I want to transfer to new version suitesparse-7.3.1 but the code does not give the desired result. With this code, I found that the factorization result L is easy to understand in the old version. For example, if L has value 3.5 at row 0 and column 0, I could see L->p points to 0, L->i points to 0 and L->x points to 3.5. However with the new version, L->p points to 0, L->i points to 1474682370 and L->x points to NULL. The select submatrix part of code would not work then.

I checked difference between old and new version in doc, but didn't find difference that can explain this behavior. Could you help to work things right? Thanks a lot.

By the way, is there a better way in selecting submatrix from L? Any APIs in cholmod to do this?

**Comment by DrTimothyAldenDavis** [comment]
Yes, that's very old code, and it won't work in the latest CHOLMOD.  It's particularly broken if L is a supernodal matrix.

The best place to look for how I traverse the data structure for L is the Check/cholmod_check.c file, where I have a cholmod_print_factor function.

I do have a submatrix function, cholmod_submatrix.  It works on a sparse matrix, not a sparse factorization, but you can convert a sparse factorization in to a sparse matrix with cholmod_factor_to_sparse.

I also have GrB_extract in GraphBLAS, if you want go to trouble of importing a CHOLMOD sparse matrix into a GrB_Matrix.  I don't yet have a connection between those two libraries, though (but I need to do one).

**Comment by ruizhi92** [comment]
> Yes, that's very old code, and it won't work in the latest CHOLMOD. It's particularly broken if L is a supernodal matrix.
> 
> The best place to look for how I traverse the data structure for L is the Check/cholmod_check.c file, where I have a cholmod_print_factor function.
> 
> I do have a submatrix function, cholmod_submatrix. It works on a sparse matrix, not a sparse factorization, but you can convert a sparse factorization in to a sparse matrix with cholmod_factor_to_sparse.
> 
> I also have GrB_extract in GraphBLAS, if you want go to trouble of importing a CHOLMOD sparse matrix into a GrB_Matrix. I don't yet have a connection between those two libraries, though (but I need to do one).

Thank you very much Dr. Davis! Very detailed and helpful answer.
