### ISSUE TITLE
SPQR build error SuiteSparse 5.4.0 on Matlab R2021b

### ISSUE THREAD

**Issue by sivantoledo** [DrTimothyAldenDavis/SuiteSparse#518]
**Describe the bug**
>> spqr_install
Compiling SuiteSparseQR with METIS for MATLAB Version 9.11.0.1809720 (R2021b) Update 1
with 64-bit BLAS

............................................................
................................................Error using mex
b64.c
C:\Programs\SuiteSparse\metis-5.1.0\GKlib\GKlib.h(68): fatal error C1083: Cannot open include file: 'regex.h': No such file or directory

**To Reproduce**
MATLAB R2021b Update 1 on Windows 11 64-bit

**Comment by sivantoledo** [comment]
Trying version 7.3.1 now to see if this will resolve the problem. I mistakenly thought that 5.4.0 is the latest.

**Comment by sivantoledo** [comment]
7.3.1 did not build either:

Error using mex
cholmod_l_aat.c
..\..\CHOLMOD\Include\cholmod_internal.h(146): error C2146: syntax error: missing ')' before identifier 'c'
..\..\CHOLMOD\Include\cholmod_internal.h(146): error C2061: syntax error: identifier 'c'
..\..\CHOLMOD\Include\cholmod_internal.h(146): error C2059: syntax error: ';'
..\..\CHOLMOD\Include\cholmod_internal.h(146): error C2059: syntax error: ','
..\..\CHOLMOD\Include\cholmod_internal.h(149): error C2059: syntax error: ')'
..\..\CHOLMOD\Include\cholmod_internal.h(760): warning C4018: '<': signed/unsigned mismatch

I also tried 5.8.1 and it failed again on the missing regex.h

**Comment by sivantoledo** [comment]
Resolved the problem by removing the metis directory from SuitSparse. Probably not an ideal solution but worked. This was with 5.8.1.

**Comment by DrTimothyAldenDavis** [comment]
I have a new method for including metis inside SuiteSparse, and it avoids the regex.h problem (a portability issue in METIS itself).

The error you see in the "check_flag" function should be fixed in my latest version on the singledev2 branch.  That function is for debugging only (which is disabled unless you edit the cholmod_internal.h file) and should be move up to be just inside the #ifndef NDEBUG part just above it, like this:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/b0f841580b1505ead8de05e4856a5598b38130b7/CHOLMOD/Include/cholmod_internal.h#L694

I'll leave this open since it should be fixed for the next stable release of CHOLMOD (v5.1) for SuiteSparse v7.4.

**Comment by DrTimothyAldenDavis** [comment]
Can you give SuiteSparse 7.4.0.beta1 a try?  This issue should be fixed there.

**Comment by sivantoledo** [comment]
Hi Tim,

Sorry for not responding earlier.

I was able to download the zip for beta5 (didn't find a beta1 release). The
build failed but with a different error:

>> cd SuiteSparse-7.4.0.beta5\
>> cd SPQR\
>> cd MATLAB\
>> spqr_install
Compiling SuiteSparseQR on MATLAB Version 9.11.0.1809720 (R2021b) Update 1
with 64-bit BLAS

............................................................
.........Error using mex
cholmod_l_aat.c
..\..\CHOLMOD\Include\cholmod_internal.h(157): error C2146: syntax error:
missing ')' before identifier 'c'
..\..\CHOLMOD\Include\cholmod_internal.h(157): error C2061: syntax error:
identifier 'c'
..\..\CHOLMOD\Include\cholmod_internal.h(157): error C2059: syntax error:
';'
..\..\CHOLMOD\Include\cholmod_internal.h(157): error C2059: syntax error:
','
..\..\CHOLMOD\Include\cholmod_internal.h(160): error C2059: syntax error:
')'



Error in spqr_make>do_cmd (line 512)
eval (s) ;

Error in spqr_make (line 481)
    kk = do_cmd (s, kk, details) ;

Error in spqr_install (line 24)
spqr_make ;

**Comment by DrTimothyAldenDavis** [comment]
Oh ... that's a Windows thing.  A "restrict" keyword snuck in there, which is C standard but MS Visual Studio gleefully breaks the C standard ...

In the short term, you can edit CHOLMOD/Include/cholmod_internal.h and delete the "restrict" keyword at line 157.  I'll fix it later on, on my end, for the next beta release.

**Comment by DrTimothyAldenDavis** [comment]
Also needs to be removed in CHOLMOD/Utility/cholmod_mult_uint64_t.c.

**Comment by DrTimothyAldenDavis** [comment]
see https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/ab43af26e3a8d48301eea859d855cf4137f0ed41

**Comment by DrTimothyAldenDavis** [comment]
Can you give 7.4.0.beta7 a try?

https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.4.0.beta7

**Comment by sivantoledo** [comment]
I found only beta8 on the releases page, gave it a try, and got this error
(again on Windows):

**Comment by sivantoledo** [comment]
I found only beta8 on the releases page, gave it a try, and got this error
(again on Windows):

Error using mex
cholmod_metis_wrapper.c
..\..\CHOLMOD\SuiteSparse_metis/GKlib/GKlib.h(101): fatal error C1083:
Cannot open include file: 'gk_types.h': No
such file or directory

Error in spqr_make>do_cmd (line 512)
eval (s) ;

Error in spqr_make (line 481)
    kk = do_cmd (s, kk, details) ;

Error in spqr_install (line 24)
spqr_make ;

----------------------------

I'll try beta6 next and will report.

**Comment by sivantoledo** [comment]
Beta 6 generates the same error, complaining that gk_types.h is missing.

**Comment by DrTimothyAldenDavis** [comment]
Odd.  That must be a Windows compiler thing, but the error doesn't occur when building SPQR on Windows outside of MATLAB.  Can you tell me what compiler MATLAB is using?  Perhaps it's an old compiler.

I can probably get this to work with your existing compiler, though.

gk_types.h is #Included into the metis source with angle brackets.  That's telling the compiler that gk_types.h is a system file, and it's a very bad idea to use angle brackets for non-system files.  I suppose most compilers find the file anyway, but it should be 

`#include "gk_types.h"
`

and not

`#Include <gk_types.h>
`

(for example).  I went through the source code of METIS (inside CHOLMOD) and took out all the angle brackets.  It still compiles for me on my Mac, but I may have missed an angle bracket or two.  I'll post a next beta release (beta10).

When I post a new beta release I delete the old one so just take beta10 or later.

See https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/631 .

Once the CI passes, I'll post a 7.4.0.beta10.

**Comment by DrTimothyAldenDavis** [comment]
I mean beta9...  Give this a try: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.4.0.beta9

If I update SuiteSparse with another beta release, just take the latest beta release you see.

**Comment by sivantoledo** [comment]
Hi Tim,

I have Microsoft Visual C++ 2019 community edition:

>> mex -setup
MEX configured to use 'Microsoft Visual C++ 2019 (C)' for C language
compilation.

I searched the installation folder
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
and didn't find a file called gk_types.h in there.

**Comment by DrTimothyAldenDavis** [comment]
gk_types.h isn't a system file. It's part of Metis and is inside the SuiteSparse_metis folder. 

That's why the #include of that and the other Metis files should have quotes not angle brackets.

**Comment by DrTimothyAldenDavis** [comment]
This should now be fixed in SuiteSparse 7.4.0.

**Comment by sivantoledo** [comment]
Hi Tim,

The include fine gk_types.h is now found, but it seems the compiler doesn't
like it's syntax:

>> spqr_install
Compiling SuiteSparseQR on MATLAB Version 9.11.0.1809720 (R2021b) Update 1
with 64-bit BLAS

............................................................
............................................................
............................................................
............................................................
.......Error using mex
cholmod_metis_wrapper.c
C:\Programs\SuiteSparse-7.4.0\CHOLMOD\SuiteSparse_metis\GKlib\gk_types.h(22):
error C2061: syntax error: identifier
'gk_idx_t'
C:\Programs\SuiteSparse-7.4.0\CHOLMOD\SuiteSparse_metis\GKlib\gk_types.h(22):
error C2059: syntax error: ';'
C:\Programs\SuiteSparse-7.4.0\CHOLMOD\SuiteSparse_metis\GKlib\gk_struct.h(24):
error C2061: syntax error:

**Comment by DrTimothyAldenDavis** [comment]
Ah, that's something I changed but hadn't been able to test on Windows in MATLAB yet.

the flags variable needs to have -DNO_SSIZE_T added to it.  After flags is created, it needs:

`flags = [flags ' -DNO_SSIZE_T'] ;
`

I'll fix it shortly.

**Comment by DrTimothyAldenDavis** [comment]
See https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/1c95f6eac6051f784b26040b707580464e5cc95a .  Can you try it on the dev2 branch?  I could post a 7.5.0.beta2 pre-release but I'm not quite ready to do that yet, for other parts of the code.

**Comment by sivantoledo** [comment]
Sure. Looks like there is progress (with a lot of warnings, probably
harmless), but now it can't find GKlib.h:

>> cd \programs\SuiteSparse-dev2\
>> cd SPQR\MATLAB\
>> spqr_install
Compiling SuiteSparseQR on MATLAB Version 9.11.0.1809720 (R2021b) Update 1
with 64-bit BLAS

............................................................
............................................................
............................................................
............................................................
.......Error using mex
cholmod_metis_wrapper.c
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(25): warning C4267: '=':
conversion from 'size_t' to 'char', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(25): warning C4244:
'initializing': conversion from 'double' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(26): warning C4267: '=':
conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(26): warning C4244:
'initializing': conversion from 'double' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(27): warning C4267: '=':
conversion from 'size_t' to 'int32_t', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(27): warning C4244:
'initializing': conversion from 'double' to 'int32_t', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(28): warning C4244:
'initializing': conversion from 'double' to 'int64_t', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(29): warning C4244:
'initializing': conversion from 'double' to 'ssize_t', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/blas.c(32): warning C4244:
'initializing': conversion from 'double' to 'gk_idx_t', possible loss of
data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/evaluate.c(34): warning C4244: '=':
conversion from 'double' to 'float', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/evaluate.c(73): warning C4244:
'return': conversion from 'double' to 'float', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/evaluate.c(101): warning C4244:
'return': conversion from 'double' to 'float', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/evaluate.c(115): warning C4244:
'return': conversion from 'double' to 'float', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/evaluate.c(131): warning C4244:
'return': conversion from 'double' to 'float', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/fkvkselect.c(27): warning C4267:
'return': conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/fkvkselect.c(29): warning C4267: '=':
conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/fkvkselect.c(91): warning C4267:
'return': conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/fkvkselect.c(93): warning C4267: '=':
conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/mcore.c(208): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/mcore.c(349): warning C4267: '=':
conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/mcore.c(377): warning C4267: '=':
conversion from 'size_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(25): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(26): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(27): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(28): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(29): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(30): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(31): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(32): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(34): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(35): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(36): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(37): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(38): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(39): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(40): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(41): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(42): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(63): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/memory.c(87): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(26): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(27): warning C4244: '=':
conversion from 'gk_idx_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(30): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(68): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(72): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(73): warning C4018: '<':
signed/unsigned mismatch
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(74): warning C4244: '=':
conversion from 'gk_idx_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(88): warning C4244: 'return':
conversion from 'gk_idx_t' to 'int', possible loss of data
..\..\CHOLMOD\SuiteSparse_metis/GKlib/util.c(106): warning C4244: 'return':
conversion from 'double' to 'float', possible loss of data
C:\Programs\SuiteSparse-dev2\CHOLMOD\SuiteSparse_metis\libmetis\metislib.h(17):
fatal error C1083: Cannot open include file: 'GKlib.h': No such file or
directory


Error in spqr_make>do_cmd (line 507)
eval (s) ;
Error in spqr_make (line 476)
    kk = do_cmd (s, kk, details) ;
Error in spqr_install (line 24)
spqr_make ;

**Comment by DrTimothyAldenDavis** [comment]
oops.  I didn't completely update the spqr_make.m file.

This should fix it: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/6047553760a6297a269e8294d99e820792eeb149

**Comment by sivantoledo** [comment]
Yep, now spqr_install completes with no warnings or errors and spqr_demo
works fine too. Thanks a lot!

Regards, Sivan

**Comment by DrTimothyAldenDavis** [comment]
I've cleaned up the spqr_make.m file and also cholmod_make.m, and posted a 7.5.0.beta3, here: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.5.0.beta3

Can you give it a try?

**Comment by sivantoledo** [comment]
Seems equally peaceful:

>> cd SuiteSparse-7.5.0.beta3\SPQR\MATLAB\
>> spqr_install
Compiling SPQR with METIS for MATLAB Version 9.11.0.1809720 (R2021b) Update
1

............................................................
............................................................
............................................................
............................................................
...........................................
SuiteSparseQR successfully compiled

The following path has been added.  You may wish to add it
permanently, using the MATLAB pathtool command.
C:\Programs\SuiteSparse-7.5.0.beta3\SPQR\MATLAB

To try your new mexFunctions, try this command:
spqr_demo

**Comment by DrTimothyAldenDavis** [comment]
Great!  I'll close this issue now.  Thanks for trying this out.  It's very useful to get the suitesparse MATLAB functions working on Windows, but it's hard for me to test them.
