### ISSUE TITLE
Testing cholmod with matrix “nd6k.mtx”, the time with cuda (Quadro RTX 6000) is slower than that of cpu (without openmp), mainly because of the analyze time.

### ISSUE THREAD

**Issue by luoyin500** [DrTimothyAldenDavis/SuiteSparse#52]
I test cholmod using matrix: nd6k (https://www.cise.ufl.edu/research/sparse/MM/ND/nd6k.tar.gz)

---------------------------------------------------------------------------
**The code is:**

int main()
{
    struct timeval t1, t2;
    double elapsedTime;

    const char* matFile = "nd6k.mtx";
    FILE* fp = fopen(matFile, "r");
    assert(fp != NULL);

    cholmod_sparse *A ;
    cholmod_dense *x, *b;
    cholmod_factor *L ;

    cholmod_common* c = (cholmod_common*)malloc(sizeof(cholmod_common));
    cholmod_l_start (c) ; /* start CHOLMOD */
    c->useGPU = 1;
    c->supernodal = CHOLMOD_SUPERNODAL;

    A = cholmod_l_read_sparse (fp, c) ; /* read in a matrix */
    cholmod_l_print_sparse (A, "A", c) ; /* print the matrix */
    fclose(fp);

    if (A == NULL || A->stype == 0) /* A must be symmetric */
    {
        cholmod_l_free_sparse (&A, c) ;
        cholmod_l_finish (c) ;
        return (0) ;
    }

    b = cholmod_l_ones (A->nrow, 1, A->xtype, c) ; /* b = ones(n,1) */

    gettimeofday(&t1, NULL);
    L = cholmod_l_analyze (A, c) ; /* analyze */
    gettimeofday(&t2, NULL); 
    elapsedTime = (t2.tv_sec - t1.tv_sec) * 1000.0;
    elapsedTime += (t2.tv_usec - t1.tv_usec) / 1000.0;
    printf("analyze Time: %.4f ms\n", elapsedTime);
    
    gettimeofday(&t1, NULL);
    cholmod_l_factorize (A, L, c) ; /* factorize */
    gettimeofday(&t2, NULL);
    elapsedTime = (t2.tv_sec - t1.tv_sec) * 1000.0;
    elapsedTime += (t2.tv_usec - t1.tv_usec) / 1000.0;
    printf("factorize Time: %.4f ms\n", elapsedTime);
    
    gettimeofday(&t1, NULL);
    x = cholmod_l_solve (CHOLMOD_A, L, b, c) ; /* solve Ax=b */
    gettimeofday(&t2, NULL);
    elapsedTime = (t2.tv_sec - t1.tv_sec) * 1000.0;
    elapsedTime += (t2.tv_usec - t1.tv_usec) / 1000.0;
    printf("solve Time: %.4f ms\n", elapsedTime);
    
    cholmod_l_gpu_stats(c);
    cholmod_l_free_factor (&L, c) ; /* free matrices */
    cholmod_l_free_sparse (&A, c) ;
    cholmod_l_free_dense (&x, c) ;
    cholmod_l_free_dense (&b, c) ;
    cholmod_l_finish (c) ; /* finish CHOLMOD */
    
    return (0) ;
}
---------------------------------------------------------------------------
**Using cpu:**
analyze Time: 1138.2430 ms
factorize Time: 10002.1580 ms
solve Time: 99.5780 ms

SYRK  CPU calls          799 time   3.4990e+00
          GPU calls            0 time   0.0000e+00
GEMM  CPU calls          628 time   2.0249e+00
             GPU calls            0 time   0.0000e+00
POTRF CPU calls          172 time   2.8340e+00
           GPU calls            0 time   0.0000e+00
TRSM  CPU calls          171 time   1.1318e+00
           GPU calls            0 time   0.0000e+00

**Using gpu**
analyze Time: 16036.8460 ms
factorize Time: 1495.4660 ms
solve Time: 158.9000 ms

SYRK  CPU calls          559 time   5.7435e-02
         GPU calls          240 time   1.0373e-01
GEMM  CPU calls          427 time   5.9693e-02
            GPU calls          240 time   3.4453e-03
POTRF CPU calls          166 time   2.6762e-02
          GPU calls            6 time   1.7808e-01
TRSM  CPU calls          166 time   3.8800e-01
          GPU calls            5 time   6.5708e-02

The analyze of gpu mode is much slower than that of cpu mode.

**I wander:**
1. Whether the calling process is correct?
2. If the calling process is correct, why the analyze of gpu is slow?

**Comment by DrTimothyAldenDavis** [comment]
The analysis phase has a lot more work to do when factorizing on the GPU.
