### ISSUE TITLE
Change CUDA::nvToolsExt to CUDA::nvtx3 with CMake 3.25+

### ISSUE THREAD

**Issue by syby119** [DrTimothyAldenDavis/SuiteSparse#530]
When compiling the SuiteSparse_GPURuntime on Windows, the CMake complains that 
```
CMake Error at CMakeLists.txt:108 (target_link_libraries):
  Target "GPURuntime" links to:

    CUDA::nvToolsExt

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I did a quick survey with the problem and find that CMake has changed the CUDA::nvToolsExt to CUDA::nvtx3 on CUDA 10+ since CMake 3.25: https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#nvtx3

I build the project with CMake 3.28.0 and CUDA 12.0 on windows, using vcpkg to provide LAPACK and BLAS.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the update.  This is now fixed in SuiteSparse 7.4.0, in the default dev branch of the SuiteSparse repo.  I'll release a 7.4.0.beta1 soon.
