### ISSUE TITLE
SPQR documentation should state that in Householder mode spqr_qmult always multiplies by a square Q

### ISSUE THREAD

**Issue by sivantoledo** [DrTimothyAldenDavis/SuiteSparse#536]
The documentation of spqr (both "help spqr" and the PDF version) states that in the econ variants, Q is rectangular.

The documentation of spqr_qmult (both in the help and in the documentation) speaks of multiplying by Q, without any reference to its dimensions.

When opts.Q=='Householder', and opts.econ==size(A,2) (with A tall and skinny), R is n by n where n=size(A,2), as we expect, but application of spqr_qmult always applies the square Q. 

This should be obvious to anybody who understands the Householder-reflectors representation, but it is surprising if you do not fully understand this.

I suggest that the documentation of spqr_qmult states explicitly, both in the help and in the PDF versions, that the function always applies the square orthonormal Q, even if opts.econ requested an economy-size factorization.

**Comment by DrTimothyAldenDavis** [comment]
That's a good idea.  I will be taking a closer look at SPQR later on, when I revise it to handle single precision sparse matrices (float and float complex).  I'll add this to the documentation then.

**Comment by DrTimothyAldenDavis** [comment]
I've gone ahead and made this change to the documentation; it will appear in SuiteSparse 7.4.0.  Thanks for the feedback!
