### ISSUE TITLE
Can't get the correct answer by using AMD and LDL

### ISSUE THREAD

**Issue by zrjer** [DrTimothyAldenDavis/SuiteSparse#54]
**Describe the bug**
Hello, if I use the default order to solve the small example  in the LDL's userguide, I can get the right answer. However, when I 
use AMD and then to solve the same example, the answer is incorrect, I donn't know the reason.
     

**Expected behavior**
The example is from LDL's userguide.
The default order is [0,1,2,3,4,5,6,7,8,9], the answer is [.1 .2 .3 .4 .5 .6 .7 .8 .9 1]
when I use AMD, the order is [2  3  5  0  7  8  6  1  4  9 ] and the answer is incorrect.

 Thank you!

**Comment by DrTimothyAldenDavis** [comment]
You are probably using LDL wrong.  Did you use the AMD example in the user guide, or did you attempt to call AMD yourself?  See the Demo/ldlmain.c which uses AMD.  It gets the right answer.

**Comment by zrjer** [comment]
Yes, I only use the upper part of the matrix. When I use the whole matrix the answer is right. Thank you very much!
