### ISSUE TITLE
CUDA11 Support

### ISSUE THREAD

**Issue by deece** [DrTimothyAldenDavis/SuiteSparse#56]
**Is your feature request related to a problem? Please describe.**
CUDA11 drops support for compute_30.

**Describe the solution you'd like**
Detect the CUDA version & conditionally include compute_30 if supported.

**Describe alternatives you've considered**
I currently manually remove support compute_30 by removing it from SuiteSparse_config/SuiteSparse_config.mk 

**Additional context**
CUDA version can be detected in make with `nvcc --version | grep -o 'release [0-9]*' | grep -o '[0-9]*'`

**Comment by TooSchoolForCool** [comment]
Does SuiteSparse support CUDA11 right now?

**Comment by deece** [comment]
It depends what you mean by support - if you mean compiles & works as expected, then this patch provides that. If you mean makes use of new features provided, then no.

**Comment by deece** [comment]
No, it fails as it hardcodes compute_30, which is not supported in CUDA11.

**Comment by TooSchoolForCool** [comment]
I see... Thank you for your reply. 

At present, I just manually remove the `compute_30` line in the cmake config file.

**Comment by wdennis** [comment]
Trying to build 5.9.0 against CUDA 11.2, I have to remove these two instances:
```
SuiteSparse-5.9.0# grep -R compute_30 *
CHOLMOD/Tcov/Makefile:  $(NVCC) -I../../SuiteSparse_config -Xcompiler -fPIC -O3  -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -c ../GPU/cholmod_gpu_kernels.cu
SuiteSparse_config/SuiteSparse_config.mk:                            -gencode=arch=compute_30,code=sm_30 \
```

**Comment by DrTimothyAldenDavis** [comment]
I've removed the compute_30 from the SuiteSparse_config.mk file.
