### ISSUE TITLE
SuiteSparse vs MATLAB : Cholesky factorization of large sparse symmetric positive definite matrix

### ISSUE THREAD

**Issue by Mbakhov** [DrTimothyAldenDavis/SuiteSparse#57]
Dear developers, 
 I have a very large sparse symmetric positive-definite matrices A with sizes ~ (200 k x 200 k) which I need to factorize; 
Matlab decomposition function AF=decomposition(A, 'chol') is solving the problem in small sizes much more faster rather then chol(A) (of matlab) and chol2(A) of SuiteSparse. The reason is unclear for me. 

I wanted to ask, whether SuiteSparse's chol2 always fast with respect to decomposition function of MATLAB? 

I attached an example matrix for your checking. 
[Achol.zip](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/5074686/Achol.zip)

Thank you, 

Best regards, 

Murod

**Comment by DrTimothyAldenDavis** [comment]
You haven't provided enough information.  All 3 use cases use my solvers underneath.  decomposition(A,'chol') uses a fill-reducing ordering, but L=chol(A) doesn't (it has no place to return the permutation to the caller).  You didn't say how you are calling chol or chol2, but I'm guessing you are disallowing the permutation with L=chol(A).  So it will naturally be slower.

**Comment by Mbakhov** [comment]
indeed, thank you.
