### ISSUE TITLE
Mongoose tests are failing (various reasons)

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [DrTimothyAldenDavis/SuiteSparse#571]
The Mongoose tests have been revised, and they now work when building Mongoose inside Mongoose/build, but they fail when using the root CMakeLists.txt.  I had to make these 3 changes to get them to work in Mongoose/build:

1. This one I had to do because python3.12 broke the tests (distutils removed): https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/0ead217e95c74b10d53e6f9ecb221b86bfe74adf
2. This change was because the cmake target name changed at some point from mongoose_lib_dbg to Mongoose_static_dgb. The new name is better but then the Mongoose tests since then were silently failing: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/afe685bb8039e3bfdad5a942391503f5a083afc2
3. This change was needed because if the directory "mongoose_lib_dbg" was not found, the tests fail but cmake thinks they pass: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/f8ec2c6415204767f3a6e42ec59c59d4049a00d9

These issues were discussed in the wrong place: https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/565 .

However, there still is an issue.  The root CMakeLists.txt builds all of SuiteSparse inside SuiteSparse/build, and as a result, the Mongoose/Tests/runTests cannot find directories in needs.  An extra "Mongoose" or "../Mongoose" needs to be added to the many paths referenced in the tests.  For example "../Source" is refered to but it would need to be "../../Mongoose/Source" if the test is run inside SuiteSparse/build instead of Mongoose/build.

Then there are reference to Mongoose_static_dbg.dir, which is also no longer in the "right place" if the tests are run inside SuiteSparse/build.

I suppose the solution is to detect where the test are being run (in SuiteSparse/build or SuiteSparse/Mongoose/build) and to revise the file locations accordingly.  Not a hard change but there are many places where the paths need to be revised.

In the meantime, the Mongoose tests will be failing when using the root CMakeLists.txt.

**Comment by DrTimothyAldenDavis** [comment]
Getting close.  The only thing failing is the MSVC tests, where downloading the test matrices via the url is causing problems.  It might be the sparse.tamu.edu website.  The site is https:// but to save costs on Amazon, the massive data files are sent over http://.  Most web browsers are fine with that so all the other systems pass, including MINGW.  But the MSVC tests complain about an ssl certificate error.

So the simplest thing to do might be to just disable the Mongoose tests that download test matrices from a url.

**Comment by mmuetzel** [comment]
Oops. I didn't notice this (and the tests said they had passed).

I opened #573 with possible changes to allow running the ctests with MSVC in the CI.

**Comment by DrTimothyAldenDavis** [comment]
Yes, the original tests weren't declaring their failure properly.  I think this issue for Mongoose is now resolved with your recent changes and my earlier ones.  I'll keep this issue open until I'm sure, but it's looking good right now.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in Suitesparse 7.4.0.beta1.
