### ISSUE TITLE
can not make 

### ISSUE THREAD

**Issue by gaotao19890725** [DrTimothyAldenDavis/SuiteSparse#58]
**Describe the bug**
[100%] Built target complex_demo
[100%] Built target import_demo
[100%] Built target openmp_demo
make[4]: Leaving directory '/home/gaotao/data/package/SuiteSparse/GraphBLAS/build'
[100%] Built target mis_demo
[100%] Built target kron_demo
make[3]: Leaving directory '/home/gaotao/data/package/SuiteSparse/GraphBLAS/build'
make[2]: Leaving directory '/home/gaotao/data/package/SuiteSparse/GraphBLAS/build'
make[1]: Leaving directory '/home/gaotao/data/package/SuiteSparse/GraphBLAS'
( cd SLIP_LU && make )
make[1]: Entering directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU'
( cd Lib ; make )
make[2]: Entering directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU/Lib'
make install INSTALL=/home/gaotao/data/package/SuiteSparse
make[3]: Entering directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU/Lib'
cc -L/home/gaotao/data/package/SuiteSparse/lib -shared -Wl,-soname -Wl,libsliplu.so.1 -Wl,--no-undefined slip_matrix_div.o slip_create_mpq_array.o SLIP_free.o SLIP_LU_factorize.o SLIP_realloc.o slip_matrix_mul.o slip_get_largest_pivot.o slip_ref_triangular_solve.o SLIP_backslash.o slip_create_mpz_array.o slip_get_nonzero_pivot.o SLIP_LU_solve.o slip_back_sub.o slip_cumsum.o slip_get_pivot.o SLIP_malloc.o slip_sparse_collapse.o SLIP_calloc.o slip_dfs.o slip_get_smallest_pivot.o SLIP_matrix_allocate.o slip_sparse_realloc.o slip_cast_array.o slip_expand_double_array.o SLIP_gmp.o SLIP_matrix_copy.o SLIP_matrix_check.o slip_cast_matrix.o slip_expand_mpfr_array.o SLIP_initialize.o SLIP_matrix_free.o slip_check_solution.o slip_expand_mpq_array.o SLIP_initialize_expert.o SLIP_matrix_nnz.o SLIP_create_default_options.o SLIP_finalize.o SLIP_LU_analysis_free.o slip_permute_x.o slip_permute_b.o slip_create_mpfr_array.o slip_forward_sub.o SLIP_LU_analyze.o slip_reach.o -o /home/gaotao/data/package/SuiteSparse/lib/libsliplu.so.1.0.2 -lm -lrt -Wl,-rpath=/home/gaotao/data/package/SuiteSparse/lib -lsuitesparseconfig -lamd -lcolamd -lm -lgmp -lmpfr
/usr/bin/ld: cannot find -lgmp
/usr/bin/ld: cannot find -lmpfr
collect2: error: ld returned 1 exit status
Makefile:69: recipe for target '/home/gaotao/data/package/SuiteSparse/lib/libsliplu.so.1.0.2' failed
make[3]: *** [/home/gaotao/data/package/SuiteSparse/lib/libsliplu.so.1.0.2] Error 1
make[3]: Leaving directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU/Lib'
Makefile:53: recipe for target 'library' failed
make[2]: *** [library] Error 2
make[2]: Leaving directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU/Lib'
Makefile:24: recipe for target 'C' failed
make[1]: *** [C] Error 2
make[1]: Leaving directory '/home/gaotao/data/package/SuiteSparse/SLIP_LU'
Makefile:18: recipe for target 'go' failed
make: *** [go] Error 2
gaotao@gaotao-desktop:~/data/package/SuiteSparse$ 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04 ARMv8 Processor rev 3 (v8l) × 4 
 - compiler [e.g. gcc 7.4, icc 19.0]
 - BLAS and LAPACK library, if applicable

**Additional context**

**Comment by gaotao19890725** [comment]
Dear DrTimothyAldenDavis, I am doing the simulation about ElasticFusion which depends on SuiteSparse, so I sudo apt-get install libsuitesparse-dev, but the result shows that "can not find Suite Sparse". Then I download the source file SuiteSparse and make, the below error occurs, can you give me some suggestions, it confuses me for a few of days.

**Comment by DrTimothyAldenDavis** [comment]
You need to either install the GMP and MPFR libraries (required by
SuiteSparse/SLIPLU), or don't install SLIPLU.
For the latter, simply comment out the "make SLIPLU" line in the top-level
Makefile.
