### ISSUE TITLE
 CholmodSupernodalLLT to solve the problem of A*x=b

### ISSUE THREAD

**Issue by xlgqut** [DrTimothyAldenDavis/SuiteSparse#592]
Hello, I would like to ask, when I use CholmodSupernodalLLT to solve the problem of A*x=b, are there any specific restrictions for matrix A? The matrix A I know should be a symmetric positive definite matrix. But when I used the following code to test some matrices A of different sizes, I found that the larger the size of most matrices, the longer it takes to solve. However, for some large-scale A, the solution time is very short. On the contrary, for some scales, the solution time is very long compared to small ones. For example, the size of sparse matrix A is nxn. A1: n=21103, of which there are 332749 non-zero values, and the solution time is 1500s; A2: n=400186, of which there are 5002517 non-zero values, and the solution time is 590s.
`Eigen::CholmodSupernodalLLT<Eigen::SparseMatrix<double>> solver; solver.compute(A); x=solver.sove(b)`

**Comment by DrTimothyAldenDavis** [comment]
The time depends strongly on the sparsity pattern, not just the size or number of entries. 

Small changes in the pattern can cause huge changes in the overall solve time. 

Except for special cases, it's not possible to predict the time for any given pattern because finding the optimal ordering is an NP complete problem.

**Comment by xlgqut** [comment]
First of all, thank you very much for replying to me despite your busy schedule. I roughly understand what you mean by the above reply, but I still want to know some questions about sparse matrix A. For example, what indicators can I use to determine whether the sparse mode of this sparse matrix A is suitable for the method CholmodSupernodalLLT? Or are there any judgment conditions that can indicate what kind of sparse matrix conforms to a good sparse pattern?
As a supplement, I provide the distribution plots of the two sparse matrices A1 and A2 mentioned first. Figure 1 is the matrix distribution diagram of A1, and Figure 2 is the matrix distribution diagram of A2.
![image](https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/153879381/2a568c6e-b56f-424c-96f1-2573fce85563)
![image](https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/153879381/0ffd47d4-26f2-40d0-954c-87bb654607f6)

**Comment by DrTimothyAldenDavis** [comment]
There are none.  It's an NP hard question. 

The only thing that you can do is to run the analysis phase and look at the results (# entries in L, and flop count).

**Comment by DrTimothyAldenDavis** [comment]
Plots of the pattern don't help to know what the final fillin/flop count will be.  A single entry in the "wrong" place (which cannot be seen in the figures) can cause the time to increase from, say, O(n) to O(n^2).

**Comment by DrTimothyAldenDavis** [comment]
I think this is resolved, as best as it can be, so I'll close it now.  If you still have questions about how to understand the ordering and operation count of sparse Cholesky, can you post it as a Discussion?
