### ISSUE TITLE
[ParU] Use unsigned integer types where it makes sense

### ISSUE THREAD

**Issue by gruenich** [DrTimothyAldenDavis/SuiteSparse#596]
**Is your feature request related to a problem? Please describe.**
In `ParU.hpp` many types are defined. They use signed integer `int64_t` instead of a unsigned integer type. Examples for values that cannot be negative are `ParU_Factors->n`, `ParU_Numeric->sym_m`, `ParU_Numeric->nf`, `ParU_Symbolic->snz`, `ParU_U_singleton->Sub`, `ParU_Control->mem_chunk`, `ParU_Control->paru_max_threads`.

**Describe the solution you'd like**
Introduce a new type like `size_t` to represent non-negative integer numbers. Technically, this is an interface change and should happen before releasing SuiteSparse 7.4.0. This change might cause additional warnings, but would add semantic meaning.

**Describe alternatives you've considered**
Sticking to the way it is.

**Additional context**
I tried to fix the following warning. It occurs as std::vector's size is a size_t. If you do not consider this change, a cast would fix this issue.

```
  SuiteSparse/ParU/Source/paru_factorize.cpp:347:27: Warning: comparison between signed and unsigned integer expressions: »std::vector<long int>::size_type« {aka »long unsigned int«} and »int32_t« {aka »int«} [-Wsign-compare]
  347 |     if (task_Q.size() * 2 > Control->paru_max_threads)
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I can help making the transition. But I would ask for a decision first and to get an unsigned type to use.

**Comment by DrTimothyAldenDavis** [comment]
I think we've resolved all of these warnings in the latest version on the dev2 branch.  ParU has undergone many changes over the past few months, and will soon be released as version 1.0.0 in the next release of SuiteSparse (v7.8.0).

I would rather stick with signed integer types throughout, and typecast when needed. Unsigned integers are hard to work with.  Loops like "for (unsigned int k = 100 ; k >= 0 ; k--)" are deceptively infinite loops, for example.  There are also cases where I use negative values like -1 to denote conditions like "unable to compute" or "not computed", for which the value zero isn't useful (it would mean "result computed and there are no entries in the matrx" or something).

The ParU objects are all becoming opaque in v1.0.0 as well, so these signed integers are not exposed to the end user application.
