### ISSUE TITLE
MacOS:  root CMakeLists.txt failing (not finding OpenMP_C)

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [DrTimothyAldenDavis/SuiteSparse#605]
@mmuetzel  :  on my Intel Mac, I'm getting errors when trying to build with the root CMakeLists.txt file.

It only occurs in some packages.  It occurs when trying to link a package with SuiteSparse_config, and I get reports like this:

```
CMake Error at Mongoose/CMakeLists.txt:222 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:OpenMP::OpenMP_C,INTERFACE_INCLUDE_DIRECTORIES>

  Target "OpenMP::OpenMP_C" not found.

...
CMake Error at SPEX/CMakeLists.txt:149 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:OpenMP::OpenMP_C,INTERFACE_INCLUDE_DIRECTORIES>

  Target "OpenMP::OpenMP_C" not found.


CMake Error at SPEX/CMakeLists.txt:154 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:OpenMP::OpenMP_C,INTERFACE_INCLUDE_DIRECTORIES>

  Target "OpenMP::OpenMP_C" not found.


CMake Error:
  Error evaluating generator expression:

    $<TARGET_PROPERTY:OpenMP::OpenMP_C,INTERFACE_INCLUDE_DIRECTORIES>

  Target "OpenMP::OpenMP_C" not found.


CMake Error at SPEX/CMakeLists.txt:154 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:OpenMP::OpenMP_C,INTERFACE_INCLUDE_DIRECTORIES>

  Target "OpenMP::OpenMP_C" not found.
```

This occurs even though OpenMP as been found.  I don't get errors in GraphBLAS, LAGraph, ParU, or CHOLMOD, just these packages:

```
mac $ ack 'Error at' typescript | uniq -c
   4 CMake Error at Mongoose/CMakeLists.txt:222 (target_link_libraries):
   4 CMake Error at Mongoose/CMakeLists.txt:248 (target_include_directories):
   4 CMake Error at Mongoose/CMakeLists.txt:262 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:272 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:287 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:306 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:327 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:349 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:366 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:394 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:408 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:416 (target_link_libraries):
   2 CMake Error at Mongoose/CMakeLists.txt:424 (target_link_libraries):
   5 CMake Error at AMD/CMakeLists.txt:138 (target_include_directories):
   5 CMake Error at AMD/CMakeLists.txt:143 (target_link_libraries):
   2 CMake Error at BTF/CMakeLists.txt:127 (target_include_directories):
   2 CMake Error at BTF/CMakeLists.txt:131 (target_include_directories):
   2 CMake Error at CAMD/CMakeLists.txt:130 (target_include_directories):
   2 CMake Error at CAMD/CMakeLists.txt:135 (target_link_libraries):
   2 CMake Error at CCOLAMD/CMakeLists.txt:127 (target_include_directories):
   2 CMake Error at CCOLAMD/CMakeLists.txt:132 (target_link_libraries):
   2 CMake Error at COLAMD/CMakeLists.txt:127 (target_include_directories):
   2 CMake Error at COLAMD/CMakeLists.txt:132 (target_link_libraries):
   2 CMake Error at CXSparse/CMakeLists.txt:162 (target_include_directories):
   2 CMake Error at CXSparse/CMakeLists.txt:167 (target_link_libraries):
   2 CMake Error at LDL/CMakeLists.txt:138 (target_include_directories):
   2 CMake Error at LDL/CMakeLists.txt:143 (target_include_directories):
   2 CMake Error at KLU/CMakeLists.txt:241 (target_include_directories):
   1 CMake Error at KLU/CMakeLists.txt:232 (target_link_libraries):
   1 CMake Error at KLU/CMakeLists.txt:274 (target_link_libraries):
   1 CMake Error at KLU/CMakeLists.txt:232 (target_link_libraries):
   1 CMake Error at KLU/CMakeLists.txt:274 (target_link_libraries):
   2 CMake Error at UMFPACK/CMakeLists.txt:167 (target_include_directories):
   2 CMake Error at UMFPACK/CMakeLists.txt:172 (target_link_libraries):
   2 CMake Error at RBio/CMakeLists.txt:128 (target_include_directories):
   2 CMake Error at RBio/CMakeLists.txt:133 (target_link_libraries):
   2 CMake Error at SPQR/CMakeLists.txt:151 (target_link_libraries):
   2 CMake Error at SPQR/CMakeLists.txt:155 (target_link_libraries):
   2 CMake Error at SPEX/CMakeLists.txt:149 (target_include_directories):
   2 CMake Error at SPEX/CMakeLists.txt:154 (target_link_libraries):
```

I'm not sure if this is because of my recent changes to revise the user-visible cmake variables.  The error occurs in any package that uses SuiteSparse_config but does not do `find_package ( OpenMP )`.

The errors do not occur in GraphBLAS, LAGraph, ParU, and CHOLMOD, and all those have a `find_package ( OpenMP ) `statement in their CMakeLists.txt file.

The errors do not occur if I use my top level Makefile instead of the top level CMakeLists.txt file.

The output of SuiteSparse_config says that it finds OpenMP just fine:

```
-- Source:           /Users/davis/dev2/SuiteSparse 
-- Build:            /Users/davis/dev2/SuiteSparse/build 
-- Install lib:      lib
-- Install include:  include/suitesparse
-- Install bin:      bin
-- Install pkg-file: lib
-- Install rpath:    
-- Build   rpath:    
-- Build type:       Release 
-- Fortran:          /Users/davis/bin/utils/spack/opt/spack/darwin-monterey-cannonlake/apple-clang-13.1.6/gcc-11.2.0-rdyxomyj7vbtjrfladbf2vm2grn4gznb/bin/gfortran
-- CUDA:             not found
-- CUDA:             not enabled
-- Building SuiteSparse_config version: v7.4.0 (Dec 30, 2023)
-- Source:           /Users/davis/dev2/SuiteSparse 
-- Build:            /Users/davis/dev2/SuiteSparse/build 
-- Install lib:      lib
-- Install include:  include/suitesparse
-- Install bin:      bin
-- Install pkg-file: lib
-- Install rpath:    
-- Build   rpath:    
-- Build type:       Release 
-- Fortran:          /Users/davis/bin/utils/spack/opt/spack/darwin-monterey-cannonlake/apple-clang-13.1.6/gcc-11.2.0-rdyxomyj7vbtjrfladbf2vm2grn4gznb/bin/gfortran
-- CUDA:             not found
-- CUDA:             not enabled
-- Looking for Intel 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for 32-bit Apple BLAS
-- Found Apple 32-bit BLAS
-- OpenMP C libraries:      /Users/davis/bin/utils/spack/opt/spack/darwin-monterey-cannonlake/apple-clang-13.1.6/gcc-11.2.0-rdyxomyj7vbtjrfladbf2vm2grn4gznb/lib/libgomp.dylib 
-- OpenMP C include:         
-- OpenMP C flags:          -fopenmp 
-- BLAS libraries:      /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Accelerate.framework 
-- BLAS linker flags:    
-- BLAS include:         
```

It's acting like linking with OpenMP just through SuiteSparse_config is failing.  All the errors are in places that link a package with SuiteSparse_config, not OpenMP directly.

Any ideas?

**Comment by DrTimothyAldenDavis** [comment]
Here are the constructed cmake files for SuiteSparse_config, if this helps:

[SuiteSparse_configTargets.cmake.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/13722923/SuiteSparse_configTargets.cmake.txt)
[SuiteSparse_configConfig.cmake.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/13722927/SuiteSparse_configConfig.cmake.txt)

**Comment by DrTimothyAldenDavis** [comment]
It looks like all I need to do is to move the `find_package ( OpenMP )` from the SuiteSparse_config/CMakeLists.txt and put it in SuiteSparsePolicy.cmake instead.  It's working on my Intel Mac; I'll push it to the repo and see if it works elsewhere.

**Comment by mmuetzel** [comment]
That might work to avoid the issue. But I don't know if that is the best solution.
Thinking of projects that might include root CMakeLists.txt of SuiteSparse as a subproject, it might be better to import those targets with global scope instead...

**Comment by Fabian188** [comment]
I do not know, if it is of interest here, but probably ...

I just installed a complete new mac and was surprised, that libomp is now installed in /opt/homebrew/opt/libomp. cmake 3.28.1 was not able to find it out of the box.
This change is from Oct 2022 and maybe did not hit me, because my own system is older.
https://github.com/Homebrew/homebrew-core/issues/112107

**Comment by DrTimothyAldenDavis** [comment]
The root CMakeLists.txt is now working on both my M1 Mac and Intel-based Mac.

I'm not sure about what to do regarding the revised homebrew OpenMP library.  I suppose I could consider a SuiteSparseOpenMP.cmake script that finds OpenMP: normally via `find_package ( OpenMP )` but if that fails, or if an OpenMP library and include file were to be explicitly set, like

`-DSUITESPARSE_OPENMP_LIB=/opt/homebrew/opt/libomp
`

then that could override the `find_package` process.  But that will take some work, and also a setup where I can try it out myself (which I don't yet have).  So I'd like to postpone that to SuiteSparse 7.5.0.

**Comment by DrTimothyAldenDavis** [comment]
I'll close this issue but if you have trouble with OpenMP in the new brew setup, can you post it as a new issue?

**Comment by Fabian188** [comment]
I consider this as a cmake bug, there is already an issue https://gitlab.kitware.com/cmake/cmake/-/issues/24097

I just wanted to comment this as there were the issues with including /opt/homebrew/include for OpenMP causing issues with brew installed SpareSuite. For a new brew installation since Oct 2022 we would not have seen this.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the heads up.

At some point it might be interesting to consider the option of passing in a known library and include file for the dependent libraries (OpenMP, BLAS, LAPACK, GMP, MPFR, etc).  I'm not sure how that would work.  It won't appear in SuiteSparse 7.4.0, which will be a stable release soon.

**Comment by Fabian188** [comment]
AFAIK cmake offers this feature by itself, but I cannot find the documentation on how to do it properly at the moment. 

E.g. the OpenMP issue for my own software was handled by setting some variables from outside.

Only with BLAS this does not work with SuiteSparse, as it sets BLA_VENDOR and other stuff before find_package( BLAS ). A test, if BLA_VENDOR is set from outside, would be a cool feature. 
In my case I just have luck, that the BLAS we configure with our own software is often the same, SuiteSparse detects when compiling the lib.

**Comment by DrTimothyAldenDavis** [comment]
You should be able to set BLA_VENDOR outside of the SuiteSparse cmake files.  In ccmake in SuiteSparse/build, for example, I changed BLA_VENDOR to Generic:

![image](https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/19956793/74e91b2c-db53-45f1-ab41-fbabb8b48c68)

and then when I generated the build system, it reported:

```
 Found BLAS: /usr/lib/x86_64-linux-gnu/libblas.so
 Found Generic 32-bit BLAS
 Specific BLAS: Generic found: TRUE
```

**Comment by mmuetzel** [comment]
Is there a way to pass linker flags for BLAS and LAPACK manually?
PETSc builds their own BLAS and LAPACK libraries, and they aren't picked up by FindBLAS or FindLAPACK.

**Comment by DrTimothyAldenDavis** [comment]
I don't have a way to do that yet.  I can try to add it for a future version.  Can you start a new issue instead, though?  This one is somewhat unrelated and now fixed except for cases where its a wider cmake issue (FindBLAS itself, as you point out).

**Comment by mmuetzel** [comment]
See #626.
