### ISSUE TITLE
How can I get the supernodal LDL^T factorization of a symmetric quasidefinite matrix ?

### ISSUE THREAD

**Issue by zrjer** [DrTimothyAldenDavis/SuiteSparse#62]
Hello, I have a question when I use CHOLMOD to solve the KKT matrix ( a symmetric quasidefinite matrix) in the interior point mathod. If I set L->is_super = false there is no problem, but if I omit this set, there is a warnning:

 CHOLMOD warning: matrix not positive definite. file: ../Supernodal/t_cholmod_super_numeric.c line: 911

The userguide tells me if L->is_super = TRUE, the supernodal LL^T factorization is computed in page 116. How can I get the supernodal LDL^T factorization of a symmetric quasidefinite matrix ? Thank you!

**Comment by DrTimothyAldenDavis** [comment]
CHOLMOD can only factorize a matrix like that with its non-supernodal
factorization method (LDL^T where D is diagonal, no 2-by-2 pivots), not the
supernodal one (which only does LL^T).

**Comment by zrjer** [comment]
I see. I want to ask a nonprofessional  question. Cholesky factorization can have supernodal and non-supernodal factorization, why dose the LDL^T only have the non-supernodal factorization ? The supernodal LDL^T is more diffcult or inefficient ？

**Comment by DrTimothyAldenDavis** [comment]
It's because I use an LAPACK function to factorize the supernode, and it
only does LL^T, but my own code for the LDL^T (which is slower, unless the
supernodes are very small in which case a non-supernodal method is faster.
Plus, I have an update/downdate method that handles the update/downdate of
LDL^T.

**Comment by zrjer** [comment]
I get it. Thank you very much !
