### ISSUE TITLE
Support setting linker flags for BLAS and LAPACK libraries manually

### ISSUE THREAD

**Issue by mmuetzel** [DrTimothyAldenDavis/SuiteSparse#626]
Currently, it is only possible to link to BLAS or LAPACK libraries that can be detected by the CMake modules FindBLAS or FindLAPACK.

Some downstream users are building SuiteSparse and try to link to their own version of those libraries (e.g., PETSc). They would need an option to by-pass those CMake modules and tell SuiteSparse to use the linker options they are providing.

**Comment by DrTimothyAldenDavis** [comment]
I'll consider this for SuiteSparse 7.5.0.  It might also be useful to be able to specify an OpenMP library manually, and perhaps GMP and MPFR for SPEX.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in SuiteSparse 7.4.0.
