### ISSUE TITLE
make finds mkl; sudo make install INSTALL=/usr/local does not find mkl

### ISSUE THREAD

**Issue by pbedenbaugh** [DrTimothyAldenDavis/SuiteSparse#63]
**Describe the bug**
make appears to complete successfully.

sudo make install INSTALL=/usr/local
make fails and terminates with 

/usr/bin/ld: cannot find -lmkl_intel_lp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_intel_thread
/usr/bin/ld: cannot find -liomp5
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:544: /usr/local/lib/libcholmod.so.3.0.14] Error 1
make[2]: Leaving directory '/home/pbedenbaugh/SuiteSparse-5.8.1/CHOLMOD/Lib'
make[1]: *** [Makefile:66: install] Error 2
make[1]: Leaving directory '/home/pbedenbaugh/SuiteSparse-5.8.1/CHOLMOD'
make: *** [Makefile:55: install] Error 2

**Desktop (please complete the following information):**
Using Windows 10 + WSL2 + Ubuntu 20.04

LIBRARY_PATH=./:/opt/intel/compilers_and_libraries_2020.3.279/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.3.279/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.3.279/linux/tbb/lib/intel64_lin/gcc4.8:/home/pbedenbaugh/intel/compilers_and_libraries_2020.2.254/linux/daal/lib/intel64_lin:/home/pbedenbaugh/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib

LD_LIBRARY_PATH=./:/opt/intel/compilers_and_libraries_2020.3.279/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.3.279/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.3.279/linux/tbb/lib/intel64_lin/gcc4.8:/home/pbedenbaugh/intel/compilers_and_libraries_2020.2.254/linux/daal/lib/intel64_lin:/home/pbedenbaugh/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib

----------------------------------------------------------------
SuiteSparse package compilation options:
----------------------------------------------------------------

SuiteSparse Version:      5.8.1
SuiteSparse top folder:   /home/pbedenbaugh/SuiteSparse-5.8.1
Package:                  LIBRARY=         libsuitesparseconfig
Version:                  VERSION=         5.8.1
SO version:               SO_VERSION=      5
System:                   UNAME=           Linux
Install directory:        INSTALL=         /home/pbedenbaugh/SuiteSparse-5.8.1
Install libraries in:     INSTALL_LIB=     /home/pbedenbaugh/SuiteSparse-5.8.1/lib
Install include files in: INSTALL_INCLUDE= /home/pbedenbaugh/SuiteSparse-5.8.1/include
Install documentation in: INSTALL_DOC=     /home/pbedenbaugh/SuiteSparse-5.8.1/share/doc/suitesparse-5.8.1
Optimization level:       OPTIMIZATION=    -O3
parallel make jobs:       JOBS=            8
BLAS library:             BLAS=            -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -liomp5 -lpthread -lm
LAPACK library:           LAPACK=
Intel TBB library:        TBB=             -ltbb
Other libraries:          LDLIBS=          -lm -lrt -Wl,-rpath=/home/pbedenbaugh/SuiteSparse-5.8.1/lib
static library:           AR_TARGET=       libsuitesparseconfig.a
shared library (full):    SO_TARGET=       libsuitesparseconfig.so.5.8.1
shared library (main):    SO_MAIN=         libsuitesparseconfig.so.5
shared library (short):   SO_PLAIN=        libsuitesparseconfig.so
shared library options:   SO_OPTS=         -L/home/pbedenbaugh/SuiteSparse-5.8.1/lib -shared -Wl,-soname -Wl,libsuitesparseconfig.so.5 -Wl,--no-undefined
shared library name tool: SO_INSTALL_NAME= echo
ranlib, for static libs:  RANLIB=          ranlib
static library command:   ARCHIVE=         ar rv
copy file:                CP=              cp -f
move file:                MV=              mv -f
remove file:              RM=              rm -f
pretty (for Tcov tests):  PRETTY=          grep -v "^#" | indent -bl -nce -bli0 -i4 -sob -l120
C compiler:               CC=              cc
C++ compiler:             CXX=             g++
CUDA compiler:            NVCC=            echo
CUDA root directory:      CUDA_PATH=
OpenMP flags:             CFOPENMP=        -fopenmp
C/C++ compiler flags:     CF=                 -O3 -fexceptions -fPIC -fopenmp
LD flags:                 LDFLAGS=         -L/home/pbedenbaugh/SuiteSparse-5.8.1/lib
Fortran compiler:         F77=             f77
Fortran flags:            F77FLAGS=
Intel MKL root:           MKLROOT=         /opt/intel/compilers_and_libraries_2020.3.279/linux/mkl/lib/intel64_lin
Auto detect Intel icc:    AUTOCC=          no
UMFPACK config:           UMFPACK_CONFIG=
CHOLMOD config:           CHOLMOD_CONFIG=
SuiteSparseQR config:     SPQR_CONFIG=
CUDA library:             CUDART_LIB=
CUBLAS library:           CUBLAS_LIB=
METIS and CHOLMOD/Partition configuration:
Your METIS library:       MY_METIS_LIB=
Your metis.h is in:       MY_METIS_INC=
METIS is used via the CHOLMOD/Partition module, configured as follows.
If the next line has -DNPARTITION then METIS will not be used:
CHOLMOD Partition config:
CHOLMOD Partition libs:    -lccolamd -lcamd -lmetis
CHOLMOD Partition include: -I/home/pbedenbaugh/SuiteSparse-5.8.1/CCOLAMD/Include -I/home/pbedenbaugh/SuiteSparse-5.8.1/CAMD/Include -I/home/pbedenbaugh/SuiteSparse-5.8.1/metis-5.1.0/include
MAKE:  make
CMake options:  -DCMAKE_INSTALL_PREFIX=/home/pbedenbaugh/SuiteSparse-5.8.1 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=cc

**Comment by pbedenbaugh** [comment]
Apologies - forgot the sudo -E option
hazards of working at night.

**Comment by DrTimothyAldenDavis** [comment]
Got it.  But I could add the "sudo -E" to the user guide, since others
might miss that.
