### ISSUE TITLE
how to build suitesparse  lib for ceres-slover in android platform ?

### ISSUE THREAD

**Issue by pjzultimate** [DrTimothyAldenDavis/SuiteSparse#64]
Hello author, I want to use SuitSparse lib on the Android OS platform. However, it appears difficult to look for reliable guidance on it.  Could you give me some suggestions?  Your help is really appreciated.

**Comment by DrTimothyAldenDavis** [comment]
I've never tried to compile any of my codes on Android OS.

A few of the packages now use cmake, and I will eventually migrate all of
the packages to use cmake as well.  That might make the Android compilation
easier, in the future.

**Comment by Eidantz** [comment]
The same Issue here got everything in my CMakeLists.txt (I only use cxsparse that my generated Matlab code was needed) the only issue that I have left with was `libcxsparse.a(cs_util_di.o) is incompatible with armelf_linux_eabi` (or any other version of android abi).
Still, there is no solution to migrate it with Android?

**Comment by DrTimothyAldenDavis** [comment]
I don't have access to any Android system.
