### ISSUE TITLE
Linux build issue

### ISSUE THREAD

**Issue by gramian** [DrTimothyAldenDavis/SuiteSparse#65]
Building SuiteSparse-5.8.1 under Ubuntu 20.04 is failing with the linker complaining that `libsuitesparseconfig` is not found.

I think the problem is in `SuiteSparse_config/SuiteSparse_config.mk`. Changing line 361 to

    LDLIBS += -L$(INSTALL_LIB) -lrt -Wl,-rpath=$(INSTALL_LIB)

(adding the library path) seems to fix the problem.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in the draft SuiteSparse v5.11.0.
