### ISSUE TITLE
Static linker flags wrong in LAGraph.pc

### ISSUE THREAD

**Issue by mmuetzel** [DrTimothyAldenDavis/SuiteSparse#656]
The static linker flags are wrong in the pkg-config file generated by LAGraph when building with the root Makefile (or as a stand-alone project). They contain something that looks like a CMake target name of GraphBLAS verbatim.
The flags in that file look ok when the file is generated with the root CMakeLists.txt.

I'm looking into the cause and a possible fix currently.

**Comment by mmuetzel** [comment]
Looking at the pkg-config files in more detail revealed a couple more issues.
I opened some PRs that should hopefully fix them: #660, #661

I'll wait if they get accepted before looking into adding CI tests for them.

**Comment by mmuetzel** [comment]
I opened #666 that adds steps to the CI which might have caught those issues earlier.

**Comment by DrTimothyAldenDavis** [comment]
I've posted a 7.5.0.beta3 with this fix: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.5.0.beta3 .

Are these issues fixed now?

**Comment by mmuetzel** [comment]
The CI step that builds the example using autotools isn't failing. It would have failed if this still was an issue.

So, this particular issue should be fixed now. 👍
