### ISSUE TITLE
Compilation issue on apple m1

### ISSUE THREAD

**Issue by nosleduc** [DrTimothyAldenDavis/SuiteSparse#69]
I'm trying to compile SuiteSparse 5.8.1 on a Mac mini with the m1 chip.
I'm using the latest version of Xcode 12.2

I have the following error:

cc    -O3 -fexceptions -fPIC -fno-common -fno-common  -I../Include -I../../COLAMD/Include -I../../AMD/Include -I../../SuiteSparse_config  -c ../Source/slip_matrix_div.c
In file included from ../Source/slip_matrix_div.c:26:
In file included from ../Source/slip_internal.h:106:
../Include/SLIP_LU.h:153:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make[3]: *** [slip_matrix_div.o] Error 1
make[2]: *** [library] Error 2
make[1]: *** [library] Error 2
make: *** [library] Error 2

OS: OSX 11.0
compiler: Apple clang version 12.0.0 (clang-1200.0.32.27)
BLAS/LAPACK: Accelerate
Version: 5.8.1

**Comment by DrTimothyAldenDavis** [comment]
That package (SLIP_LU) is looking for the GMP and MPFR libraries.  Do those
exist on the M1?

**Comment by nosleduc** [comment]
I have compiled gmp and mpfr from sources. It works now. It is strange, I do not remember doing that on OSX 10.15.
Thanks
