### ISSUE TITLE
Mongoose CMake build fails

### ISSUE THREAD

**Issue by drdas** [DrTimothyAldenDavis/SuiteSparse#70]
**Describe the bug**
[ 74%] Linking CXX executable bin/mongoose
/usr/bin/ld: cannot find -lsuitesparseconfig

**To Reproduce**
Choose custom path for INSTALL and do regular - make install INSTALL="my_PATH" 

**Expected behavior**
Mongoose build fails as it cannot find suitesparseconfig.so to link against

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - compiler: GCC 7.5
 - BLAS and LAPACK library, if applicable
 - Version 5.8.0

**Additional context**

**Comment by wdennis** [comment]
Having the same issue, on 5.9.0... My build command is:

```
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/opt/suitesparse-5.9.0/lib \
    make -j4 \
    BLAS=-lopenblas \
    CUDA_PATH=/usr/local/cuda \
    INSTALL=/opt/suitesparse-5.9.0 \
    MY_METIS_LIB=/usr/lib/x86_64-linux-gnu/libmetis.so \
    MY_METIS_INC=/usr/include \
    install
```
It did build and install `libsuitesparseconfig.so` into the specified path `/opt/suitesparse-5.9.0/lib/`, which is included in the `LD_LIBRARY_PATH` env setting for the make command:
```
# ls -l /opt/suitesparse-5.9.0/lib/
total 16
lrwxrwxrwx 1 root root    29 Apr 23 11:33 libsuitesparseconfig.so -> libsuitesparseconfig.so.5.9.0
lrwxrwxrwx 1 root root    29 Apr 23 11:33 libsuitesparseconfig.so.5 -> libsuitesparseconfig.so.5.9.0
-rwxr-xr-x 1 root root 12968 Apr 23 11:33 libsuitesparseconfig.so.5.9.0
```
But yet I'm getting `/usr/bin/ld: cannot find -lsuitesparseconfig` when it tries `linking CXX executable bin/mongoose` (& thereafter on other linking steps)

Any suggestions?

OS: *Ubuntu 18.04.5*
compiler: *cmake version 3.20.1 / GCC 7.5.0*
BLAS and LAPACK library, if applicable: *OpenBLAS 0.2.20*
Version: *5.9.0*

**Comment by wdennis** [comment]
Fixed by adding the following param to make:
`LDFLAGS=-L/opt/suitesparse-5.9.0/lib \`

(as in my case the INSTALL path was `/opt/suitesparse-5.9.0` )
