### ISSUE TITLE
Location of libcublas and libcudart

### ISSUE THREAD

**Issue by girgink** [DrTimothyAldenDavis/SuiteSparse#71]
**Describe the bug**
While compiling CHOLMOD it is assumed that libcublas.so and libcudart.so are located in the same directory, e.g. /usr/local/cuda-10.2/lib64. However, they might be located in different directories. In my case, which can be similar for other Debian/Ubuntu systems:

libcublas: /usr/lib/aarch64-linux-gnu/
libcudart: /usr/local/cuda-10.2/lib64

**To Reproduce**
`make install` 

**Expected behavior**
Compilation should check LD_LIBRARY_PATH as well.

**Desktop:**
 - OS: Ubuntu 20.04 (ARM v8.2, NVIDIA Jetson AGX)
 - compiler gcc 9.3.0
 - CUDA 10.2
 - Version 5.6.0

**Comment by mhtrinhLIC** [comment]
I also have a non-standard installation of Cuda (11.0.2)
I did not have any issue compiling. Here are my export :
```
# Using CUDA 11
CUDAPATH=/data/opt/cuda/cuda-11.0.2
export PATH="$CUDAPATH/bin:$PATH"

# Need this for the demo during the make
export LD_LIBRARY_PATH="$CUDAPATH/lib64:$LD_LIBRARY_PATH"
```

After that, just `make config` and I get : 
```
----------------------------------------------------------------
SuiteSparse package compilation options:
----------------------------------------------------------------

SuiteSparse Version:      5.10.1
[...]
CUDA library:             CUDART_LIB=      /data/opt/cuda/cuda-11.0.2/lib64/libcudart.so
CUBLAS library:           CUBLAS_LIB=      /data/opt/cuda/cuda-11.0.2/lib64/libcublas.so
[...]
```

**Comment by DrTimothyAldenDavis** [comment]
This should be fixed with the new CMake structure.  SuiteSparse_config.mk is now gone entirely (yay!).
