### ISSUE TITLE
cholmod_write error

### ISSUE THREAD

**Issue by yhg926** [DrTimothyAldenDavis/SuiteSparse#75]
**Describe the bug**
cholmod_write errors:
it report errors like this:
"CHOLMOD error: error reading/writing file. file: ../Check/cholmod_write.c line: 635"
all cholmod_write_sparse, cholmod_write_dense, cholmod_write_factor report the same error.
So there is no way to see the solution x,b or even A.
**To Reproduce**
========Here is my code========
#include <unistd.h>
#include <assert.h>
#include <sys/time.h>
#include "../include/cholmod.h"

int main (void)
{
    struct timeval t1, t2;
    double elapsedTime;

    const char* matFile = "/home/hgyi/tools/SuiteSparse/test/nd24k/nd24k.mtx";
    FILE* fp = fopen(matFile, "r");
    assert(fp != NULL);

    cholmod_sparse *A ;
    cholmod_dense *x, *b;
    cholmod_factor *L ;

    cholmod_common* c = (cholmod_common*)malloc(sizeof(cholmod_common));
    cholmod_start (c) ; /* start CHOLMOD */
  //  c->useGPU = 1;
  //  c->supernodal = CHOLMOD_SUPERNODAL;

    A = cholmod_read_sparse (fp, c) ; /* read in a matrix */
    cholmod_print_sparse (A, "A", c) ; /* print the matrix */
    fclose(fp);
	const char* outFile2 = "/home/hgyi/tools/SuiteSparse/test/out2.txt";
	FILE* fout2 = fopen(outFile2, "w");
    assert(fout2!=NULL);
	cholmod_write_sparse(fout2,A,NULL,"A",c);
    if (A == NULL  || A->stype == 0) /* A must be symmetric */
    {
        cholmod_free_sparse (&A, c) ;
        cholmod_finish (c) ;
        return (0) ;
    }

    b = cholmod_ones (A->nrow, 1, A->xtype, c) ; /* b = ones(n,1) */

    gettimeofday(&t1, NULL);
    L = cholmod_analyze (A, c) ; /* analyze */
    cholmod_factorize (A, L, c) ; /* factorize */
    x = cholmod_solve (CHOLMOD_A, L, b, c) ; /* solve Ax=b */
	const char* outFile = "/home/hgyi/tools/SuiteSparse/test/out.txt";
//	const char* outFile2 = "/home/hgyi/tools/SuiteSparse/test/out2.txt";
	FILE* fout = fopen(outFile, "w");
	assert(fout!=NULL);
	if(cholmod_check_factor(L,c)){
		cholmod_write_sparse(fout,A,NULL,"A",c);
	}

    gettimeofday(&t2, NULL);
    elapsedTime = (t2.tv_sec - t1.tv_sec) * 1000.0;
    elapsedTime += (t2.tv_usec - t1.tv_usec) / 1000.0;
    printf("Time: %.4f ms\n", elapsedTime);
    cholmod_gpu_stats(c);
    cholmod_free_factor (&L, c) ; /* free matrices */
    cholmod_free_sparse (&A, c) ;
    cholmod_free_dense (&x, c) ;
    cholmod_free_dense (&b, c) ;
    cholmod_finish (c) ; /* finish CHOLMOD */
    return (0) ;
}

========here is my make file ========
CC = gcc

CFLAGS = -g -Wall -O2 \
-lrt \
-gdwarf-2 \
-lblas \
-llapack \
-DNPARTITION

LPATH = /home/hgyi/tools/SuiteSparse/lib
LIBS = $(LPATH)/libcholmod.so \
$(LPATH)/libamd.so \
$(LPATH)/libcolamd.so \
$(LPATH)/libcamd.so \
$(LPATH)/libccolamd.so \
$(LPATH)/libsuitesparseconfig.so \
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudart.so \
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcublas.so

HEADER_DIR = $(CHOLMOD)/Include
CONFIG_HEADER_DIR = $(SUITESPARSE)/SuiteSparse_config

OBJ_DIR = .

BIN_DIR = .

INCLUDES = -I$(HEADER_DIR) \
-I$(CONFIG_HEADER_DIR)

SRCS = $(shell ls *.c)

OBJS = $(SRCS:.c=.o)

OBJS_BUILD = $(shell ls $(OBJ_DIR)/*.o)

APP = prog

RM = rm -f

all: $(APP)

$(APP): $(OBJS)
	$(CC) $(CFLAGS) -o $(BIN_DIR)/$(APP) $(OBJS_BUILD) $(LIBS)

%.o: %.c $(HEADER_DIR)/*.h $(CONFIG_HEADER_DIR)/*.h
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $(OBJ_DIR)/$@

clean:
	$(RM) $(OBJS_BUILD) $(APP)
========here is my matrix file=====
https://www.cise.ufl.edu/research/sparse/matrices/ND/nd24k.html
======my command====
./prog

**Expected behavior**
write the solution x b and A to file  , not report error

**Screenshots**
![Screen Shot 2021-02-06 at 11 26 44 PM](https://user-images.githubusercontent.com/16019807/107122444-c9068280-68d2-11eb-95c9-84febd403ff7.png)
.

**Desktop (please complete the following information):**
 - OS: unbuntu 18.04.1 LTS (Bionic Beaver)
 - compiler: gcc version 5.5.0 (Homebrew gcc 5.5.0_4)
 - BLAS and LAPACK library, if applicable
 - Version: SuiteSparse VERSION 5.8.1

**Additional context**

**Comment by DrTimothyAldenDavis** [comment]
Check to make sure you are able to write to the fout file.  This error
occurs only when fprintf returns an error.

After you open the file, but before you call cholmod-write_sparse, try this:

int ok = fprintf (fout, "test\n") ;
printf ("ok: %d\n", ok);

if that prints a negative number, then cholmod_write_sparse will fail too,
and it's
outside my control.

**Comment by DrTimothyAldenDavis** [comment]
The error could also occur if you run out of disk space in the middle.
