### ISSUE TITLE
Windows 10 building SuiteSparse as shared libraries linker problem

### ISSUE THREAD

**Issue by squidovado** [DrTimothyAldenDavis/SuiteSparse#82]
I tried to build SuiteSparse on Windows 10 with cmake configuration from Jose Luis Blanco-Claraco's repository https://github.com/jlblancoc/suitesparse-metis-for-windows
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/257b2ba2a5b40b893bff203626331b4b9c96d681/SuiteSparse_config/SuiteSparse_config.h#L96
This line caused undefined reference error when I tried to build SuiteSparse as Windows shared libraries (e. g. when building libamd.dll). I guess that "extern" here can be replaced with some macro which would as well work for the case of .dll build. Would this rather be done here or in his repository? I see that he didn't want to change your source code while making his cmake configuration, so maybe it should be done in the main SuiteSparse repo.

**Comment by DrTimothyAldenDavis** [comment]
Unsure .. I don't know what it should look like on Windows.
