### ISSUE TITLE
Modularizing METIS

### ISSUE THREAD

**Issue by Foadsf** [DrTimothyAldenDavis/SuiteSparse#83]
**Is your feature request related to a problem? Please describe.**
As I have also requested [here on Elmer's repository](https://github.com/ElmerCSC/elmerfem/issues/203), placing an entire library inside the code base is not a good practice. 

**Describe the solution you'd like**
The ideal solution would be that we have one single METIS repository that is agreed upon by all the downstream projects and then it would be added to package managers such as Conan or vcpkg.

**Describe alternatives you've considered**
If that's not a possibility, then the second-best option is just to isolate the current [METIS folder](https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/master/metis-5.1.0) and place it into a separated repository and then use [Git Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to virtually include it in the repository.

**Comment by gruenich** [comment]
Citing from the README.md:

> Some codes optionally use METIS 5.1.0. This package is located in SuiteSparse in the metis-5.1.0 directory. Its use is optional, so you can remove it before compiling SuiteSparse, if you desire. The use of METIS will improve the ordering quality. METIS has been slightly modified for use in SuiteSparse; see the metis-5.1.0/README.txt file for details. SuiteSparse can use the unmodified METIS 5.1.0, however. To use your own copy of METIS, or a pre-installed copy of METIS use 'make MY_METIS_LIB=-lmymetis' or 'make MY_METIS_LIB=/my/stuff/metis-5.1.0/whereeveritis/libmetis.so MY_METIS_INC=/my/stuff/metis-5.1.0/include'. If you want to use METIS in MATLAB, however, you MUST use the version provided here, in SuiteSparse/metis-5.1.0. The MATLAB interface to METIS required some small changes in METIS itself to get it to work. The original METIS 5.1.0 will segfault MATLAB.

As far as I understand this:
* Conan and vcpkg can create a package and safely remove the metis-5.1.0 folder in this process.
* The folder cannot be removed, as SuiteSparse needs a modification, otherwise Matlab will segfault.

It might be a good idea to fix the cause of the Matlab segfault within Metis. Having a fixed Metis release would be great.

**Comment by PMeira** [comment]
> Having a fixed Metis release would be great.

Yes, the main issue seems to be that METIS has not been updated for a while.
An updated "source of truth" for METIS would simplify or remove these issues, and the patches to workaround the MATLAB segfault could probably be integrated there. Right now a lot of projects have small patches floating around.

From its site, the sequential METIS library was last updated in 2013. Has anyone tried to contact the authors to clarify if it's still being maintained there? MT-METIS had release in 2020 and it includes most of METIS itself, but I just compared them now and there are no source code differences in that included version (i.e. the metis subfolder from the MT-METIS 2020 release is basically the same as the METIS release from 2013). Some of the bug reports on its tracker include fixes but I didn't see any reply, and the forum seems dead.

To build METIS with MSVC, even with the code from SuiteSparse, I needed [a small patch](https://github.com/dss-extensions/klusolve/blob/6329f7d69048b159ba466f42afb4b67008a07e3f/src/metis.patch).

Looking now, the [vcpkg package for METIS](https://github.com/microsoft/vcpkg/tree/105456798402aa5f494ffeb3b19dd0d870656d39/ports/metis) also includes a few patches -- the code there seems to be MIT licensed, so a conan recipe could reuse the patches. And note that there are also some other METIS "forks" here on GitHub.

**Comment by PMeira** [comment]
Looking further on GitHub, I believe this is the updated location: https://github.com/KarypisLab/METIS

I believe the ideal is to contribute patches there and point conan/vcpkg to use that repository.

**Comment by DrTimothyAldenDavis** [comment]
I'll see about updating my code so it points to the metis github.

**Comment by DrTimothyAldenDavis** [comment]
See the description of changes I have to make to METIS to use it in SuiteSparse:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/SuiteSparse_metis/include/SuiteSparse_metis.h

I would like to use the canonical METIS and GKLIB, but it doesn't work inside SuiteSparse.  In particular, I have to have control over which malloc/calloc/realloc/free is used.

To avoid any confusion, in the latest version of SuiteSparse (v6.0.0) I've renamed my compiled copy of METIS as SuiteSparse_metis.  The SuiteSparse_metis package is a nearly identical copy of METIS (under George Karypis' copyright and license), but with my edits so I can make it work inside SuiteSparse.
