### ISSUE TITLE
Build error on NetBSD due to dl

### ISSUE THREAD

**Issue by ktnb-netbsd** [DrTimothyAldenDavis/SuiteSparse#837]
**Describe the bug**
While attempting to update the version of suitesparse in pkgsrc I get the following error:
```
[ 93%] Linking C shared library libgraphblas.so
ld: cannot find -ldl
--- GraphBLAS/libgraphblas.so.9.1.0 ---
*** [GraphBLAS/libgraphblas.so.9.1.0] Error code 1
```
This happens sometimes and is very common. So much that we have a way to bypass these types of errors. That being said, it would be nice if this error were fixed upstream. NetBSD doesn't have libdl.

**To Reproduce**
Try to build wip/suitesparse on NetBSD.

**Expected behavior**
Since NetBSD doesn't have libdl, it would be expected that cmake would not check for libdl on NetBSD. I'm not sure if this is true on other BSDs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: NetBSD
 - compiler: gcc 10.5
 - Version: 7.7.0

**Comment by mmuetzel** [comment]
Thank you for your report.

Linking to libdl is currently conditional on a platform check in GraphBLAS (`NOT WIN32`).
It should probably depend on a feature test instead (ability to link to libdl).

I'm working on a PR for that.

**Comment by mmuetzel** [comment]
See PR #838 for a potential fix.

Does that check do the right thing on NetBSD?

**Comment by ktnb-netbsd** [comment]
> See PR #838 for a potential fix.
> 
> Does that check do the right think on NetBSD?

Yes, that looks like it would work. Thank you!

**Comment by ktnb-netbsd** [comment]
@mmuetzel I'll pull down the changes and attempt a build to make sure once I've got a minute.

**Comment by ktnb-netbsd** [comment]
@mmuetzel I have verified that you're change works! Thank you!

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the heads about NetBSD.  I've merged in the changes to the CMake build system, into the dev2 branch.

**Comment by ktnb-netbsd** [comment]
> Thanks for the heads about NetBSD. I've merged in the changes to the CMake build system, into the dev2 branch.

Great, thank you. Once the update goes live I'll be sure to merge it into pkgsrc-current.
