### ISSUE TITLE
allocate work momery outside of umfpack function

### ISSUE THREAD

**Issue by DragonPara** [DrTimothyAldenDavis/SuiteSparse#842]
**Is your feature request related to a problem? Please describe.**
I want to allocate work momery by my main function, I found a series of umfpack_wsolve. 

**Describe the solution you'd like**
I want some umfpack_wnumeric and umfpack_wsymbolic function like this.

**Comment by DrTimothyAldenDavis** [comment]
It would be a nice feature but it's not possible.  Sparse LU factorization is a very dynamic problem; the space required depends on the pivot ordering, which is not known until during numerical factorization.
