### ISSUE TITLE
SPEXpy: invalid memory write by strcpy()

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#847]
On this line:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/26ababc7f3af725c5fb9168a1b94850eab74b666/SPEX/Python/SPEXpy/Source/spex_python_connect.c#L146

The buffer allocated is not large enough. One more byte needs to be allocated for the null terminal.

**Comment by mmuetzel** [comment]
Thank you for reporting this issue.

I opened #851 with the fix you pointed out.
