### ISSUE TITLE
SPEXpy: invalid reference to scipy.Inf

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#848]
At least on Debian, the following line triggers an error:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/26ababc7f3af725c5fb9168a1b94850eab74b666/SPEX/Python/SPEXpy/cholesky_backslash.py#L34

There is apparently no `scipy.Inf`. Replacing it with `numpy.Inf` fixes it.

**Comment by LoreMD** [comment]
Thanks for reporting.
This has been fixed in SPEX 3.2.0.

**Comment by DrTimothyAldenDavis** [comment]
It's been fixed here:  https://github.com/clouren/SPEX/tree/SPEX-3.2.0 .
We'll copy those changes into the SuiteSparse repo here.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in SuiteSparse 7.8.0
