### ISSUE TITLE
SPEXpy: invalid setup.py

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#849]
The `setup.py` file distributed with SPEXpy has at least two problems:
- it contains spurious non-breakable whitespaces in the `install_requires` field. They need to be replaced by regular ones, otherwise `setuptools` complains (at least on Debian)
- it cannot find the `SPEXpy` module because of the non-standard layout. This file should ideally be moved to the upper directory level, so that it sees `SPEXpy` in a subdirectory.

**Comment by LoreMD** [comment]
Thanks for reporting.
This has been fixed in SPEX 3.2.0.

**Comment by DrTimothyAldenDavis** [comment]
It's been fixed here:  https://github.com/clouren/SPEX/tree/SPEX-3.2.0 .
We'll copy those changes into the SuiteSparse repo here.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in SuiteSparse 7.8.0.
