### ISSUE TITLE
build system: Support staged installs via `DESTDIR`

### ISSUE THREAD

**Issue by paulmenzel** [DrTimothyAldenDavis/SuiteSparse#86]
Currenty, the variable `INSTALL` seems to be used as [prefix][1], which for CMake is [`CMAKE_INSTALL_PREFIX`][2].

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/257b2ba2a5b40b893bff203626331b4b9c96d681/SuiteSparse_config/SuiteSparse_config.mk#L60-L86

[Packagers often require support for *staged installs*.][3] From [CMake documentation][2]:

> On UNIX one can use the DESTDIR mechanism in order to relocate the whole installation. See [DESTDIR](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html#envvar:DESTDIR) for more information.

It’d be great, if the install target could be extended to support the variable `DESTDIR`.

[1]: https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html#Directory-Variables
[2]: https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html
[3]: https://www.gnu.org/software/make/manual/html_node/DESTDIR.html#DESTDIR

**Comment by DrTimothyAldenDavis** [comment]
Yes, this is something I plan on doing, as part of my migration to cmake.

**Comment by kiwifb** [comment]
I just tested a staged install straight from the tarball with
```
make global CMAKE_INSTALL_PREFIX=/usr
make install CMAKE_INSTALL_PREFIX=/usr DESTDIR=${somewhere_in_my_home}
```
and it worked like a charm. I'd say that is pretty much fixed in 6.0.1.

**Comment by kiwifb** [comment]
Actually scratch that, I didn't notice but it didn't use `/usr` but `/usr/local`. I probably did not read the instruction properly. Checking.

**Comment by kiwifb** [comment]
It should be
```
make global CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/usr"
```

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the update.  I'll close this issue then.

**Comment by paulmenzel** [comment]
Probably it was fixed by the update from 5.13.0 to 6.0.0 in commit ad1b08927bf7 (to SuiteSparse v6.0.0), where `SuiteSparse_config/SuiteSparse_config.mk` was removed, and the change-log says:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/d42beebdcc6b98c7fb2f7f2927f32c19e0f602d0/ChangeLog#L3

**Comment by DrTimothyAldenDavis** [comment]
Yes -- the new cmake build system should be doing the right thing for staged installs.

I also have a non-default "local install" option that installs into SuiteSparse/lib, SuiteSparse/include, and SuiteSparse/bin, as a built-in type of staged install. See:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/4faadddd6d373e1b85f567dc034e9eb9733247c7/SuiteSparse_config/cmake_modules/SuiteSparsePolicy.cmake#L26

The default "global install" installs into the CMAKE_INSTALL_PREFIX.  Changing that will change where "make install" will install the compiled libraries and include.h files.

**Comment by DrTimothyAldenDavis** [comment]
DESTDIR should also work, since this environment variable modifies CMAKE_INSTALL_PREFIX (but I haven't tried it):

https://cmake.org/cmake/help/latest/envvar/DESTDIR.html#envvar:DESTDIR

**Comment by kiwifb** [comment]
I tested `DESTDIR` and it behaved as expected for me.
