### ISSUE TITLE
Different rules for negative Q [k]

### ISSUE THREAD

**Issue by DragonPara** [DrTimothyAldenDavis/SuiteSparse#865]
package: 
BTF

file: https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/131471310ef0600b231b8fa7c10a55c3f70afbd9/BTF/MATLAB/drawbtf.m#L19C17-L19C18

j = BTF_UNFLIP (Q [k]) in BTF/Source/btf_order.c
j = abs(Q[k]) in BTF/MATLAB/drawbtf.m

**Comment by DrTimothyAldenDavis** [comment]
MATLAB is 1-based while the C interface is zero-based. I thus must convert the return values of the C code from 0 to 1 based. 

That's why the logic is different in these two places.

**Comment by DrTimothyAldenDavis** [comment]
That is, in the MATLAB interface to dmperm and BTF, I add one to each entry in the array Q returned from the C code, to return 1-based indices to MATLAB.
