### ISSUE TITLE
** On entry to DPOTRF parameter number  4 had an illegal value

### ISSUE THREAD

**Issue by tduretz** [DrTimothyAldenDavis/SuiteSparse#879]
Dear SuiteSparse team,

I'm using SuiteSparse in a geodynamic modelling code for several years, on many different platforms without problem until yesterday.
I installed the code on a cluster, compilations was successful but all my test runs fail with error message :
`** On entry to DPOTRF parameter number  4 had an illegal value`
It looks like this relates to blas, somehow. The same tests would work without problem on other computers and I am not sure how to solve the issue. Would someone have hints?

*What I tried so far* (which did not help):
- installing openblas and suitesparse from the spack package manager
- installing suitesparse from source (not using spack)
- downgrading version of blas via the spack package manager
- check manually for infs and nans in my matrix (in my code)
- activate cholmod matrix check prior to analysis (in my code)

Also, is there a C equivalent to MATLAB's SuiteSparse_demo.m such that I could check that my SuiteSpars install works as expected (then it would indicate an issue with my code). 

Thanks in advance for any hint!

**Comment by DrTimothyAldenDavis** [comment]
It's probably an integer size mismatch. CHOLMOD thinks it's one thing and the BLAS thinks it's another. 

Check to see which BLAS library is being found the SuiteSparse cmake (32 vs 64 bit). Then check what your application is linking against. 

This is a common problem that is hard to guard against because there is no standard in the BLAS where I can check or assert its integer sizes for its integer parameters.

**Comment by tduretz** [comment]
Thanks for the answer!
So for my application, I see this
```
[duretz@fuchs MDLIB]$ ldd RiftingChenin
	linux-vdso.so.1 (0x00007ffcf3dc5000)
	libz.so.1 => /lib64/libz.so.1 (0x0000147bc8552000)
	libhdf5.so.200 => /lib64/libhdf5.so.200 (0x0000147bc8000000)
	libm.so.6 => /lib64/libm.so.6 (0x0000147bc8477000)
	liblapack.so.3 => /lib64/liblapack.so.3 (0x0000147bc7800000)
	libcxsparse.so.4 => /home/amdjulia/duretz/SuiteSparse/lib/libcxsparse.so.4 (0x0000147bc8443000)
	libumfpack.so.6 => /home/amdjulia/duretz/SuiteSparse/lib/libumfpack.so.6 (0x0000147bc7f35000)
	libamd.so.3 => /home/amdjulia/duretz/SuiteSparse/lib/libamd.so.3 (0x0000147bc8432000)
	libcholmod.so.5 => /home/amdjulia/duretz/SuiteSparse/lib/libcholmod.so.5 (0x0000147bc75e9000)
	libcolamd.so.3 => /home/amdjulia/duretz/SuiteSparse/lib/libcolamd.so.3 (0x0000147bc8429000)
	libbtf.so.2 => /home/amdjulia/duretz/SuiteSparse/lib/libbtf.so.2 (0x0000147bc8423000)
	libsuitesparseconfig.so.7 => /home/amdjulia/duretz/SuiteSparse/lib/libsuitesparseconfig.so.7 (0x0000147bc841e000)
	libc.so.6 => /lib64/libc.so.6 (0x0000147bc7200000)
	libsz.so.2 => /lib64/libsz.so.2 (0x0000147bc8412000)
	/lib64/ld-linux-x86-64.so.2 (0x0000147bc857b000)
	libblas.so.3 => /lib64/libblas.so.3 (0x0000147bc755f000)
	libgfortran.so.5 => /lib64/libgfortran.so.5 (0x0000147bc6e00000)
	libopenblas.so.0 => /lib64/libopenblas.so.0 (0x0000147bc4800000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x0000147bc7515000)
	libcamd.so.3 => /home/amdjulia/duretz/SuiteSparse/lib/libcamd.so.3 (0x0000147bc8402000)
	libccolamd.so.3 => /home/amdjulia/duretz/SuiteSparse/lib/libccolamd.so.3 (0x0000147bc7508000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x0000147bc74c1000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000147bc74a6000)
```
Note sure how to obtain a similar report for SuiteSparse but during `make`, I see:
```
-- Looking for Intel 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Looking for 32-bit Apple BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Looking for ARM 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Looking for IBM ESSL 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Looking for 32-bit OpenBLAS
-- Found OpenBLAS 32-bit BLAS
-- ParU frontal tree tasking: parallel
-- OpenMP C++ libraries:    /usr/lib/gcc/x86_64-redhat-linux/11/libgomp.so;/usr/lib64/libpthread.a
-- OpenMP C++ include:
-- OpenMP C++ flags:        -fopenmp
-- BLAS libraries:      /home/amdjulia/duretz/spack/opt/spack/linux-almalinux9-ivybridge/gcc-11.4.1/openblas-0.3.28-2zqgpx6y7q4vts76q4zayebzkerym76w/lib/libopenblas.so
` ``
So there is indeed likely a conflict as one openblas lives in `lib64` and the other apparently 32-bit.

**Comment by DrTimothyAldenDavis** [comment]
Hard to say. Lib64 doesn't mean it's a 64 bit BLAS.

**Comment by mmuetzel** [comment]
~~The output you are showing is hard to read. Maybe, consider using block code (triple backticks).~~ (Thanks for fixing that!)

From what I can tell, you are linking to at least three different BLAS implementations at the same time:
* `libblas.so.3 => /lib64/libblas.so.3 (0x0000147bc755f000)`
* `libopenblas.so.0 => /lib64/libopenblas.so.0 (0x0000147bc4800000)`
* `/home/amdjulia/duretz/spack/opt/spack/linux-almalinux9-ivybridge/gcc-11.4.1/openblas-0.3.28-2zqgpx6y7q4vts76q4zayebzkerym76w/lib/libopenblas.so`

That is probably not a good idea.

Try to use only one single BLAS implementation for everything.

**Comment by DrTimothyAldenDavis** [comment]
Lib64 means sizeof(void*) is 64. It has nothing to do with the size of the integer parameters to the BLAS

**Comment by tduretz** [comment]
Excellent, thanks a lot to both of you!
I have now traced back who was linking to other BLAS libraries. 
In fact I was linking my app to a lapack which was different to that used for making SuiteSparse.
So, you were both right. Thanks again for your help!

**Comment by DrTimothyAldenDavis** [comment]
I should probably add something to this effect in the top level README. "If you get an error like this, check if you are telling suitesparse it has a 64 bit BLAS when it actually has a 32 bit BLAS or visa versa, where 32/64 is not lib32/64 and not the sizeof(void*), but the size of the plain integers passed to the Fortran API of the BLAS. Etc..."
