### ISSUE TITLE
SLIP_gmp.c:(.text+0x2874): undefined reference to `mpfr_get_q'

### ISSUE THREAD

**Issue by themaddoctor** [DrTimothyAldenDavis/SuiteSparse#88]
**Describe the bug**
Cannot compile.

SLIP_gmp.c:(.text+0x2874): undefined reference to `mpfr_get_q'

**To Reproduce**
make

**Expected behavior**
complete build

**Screenshots**

**Desktop (please complete the following information):**
linux (generic)
gcc 7.3.0
mpfr 3.1.2
blas 3.9.1

**Additional context**

**Comment by DrTimothyAldenDavis** [comment]
The SLIP package requires the MPFR and GMP packages.  Are they installed
properly?

**Comment by themaddoctor** [comment]
yes

**Comment by cjh10644** [comment]
mpfr_get_q is new function to GNU MPFR version 4.0.0 (released on 25 December 2017), see https://www.mpfr.org/mpfr-4.0.0/

You need to have that version at least.

**Comment by themaddoctor** [comment]
OK, that fixed that problem. I will start a new issue for the next one.
Thank you.
