### ISSUE TITLE
`clang` implementation of `openMP` for mac builds support?

### ISSUE THREAD

**Issue by enzbus** [DrTimothyAldenDavis/SuiteSparse#886]
Hello and thank you for this marvelous software. Is compilation on MacOS using Apple's clang implementation of openMP supported? I'm building a [simple wrapper of SPQR in Python](https://github.com/enzbus/pyspqr) with pre-built wheels and it appears cmake didn't find openMP on the mac builds. [According to the llvm developers](https://blog.llvm.org/2015/05/openmp-support_22.html)

>To enable OpenMP, just add `-fopenmp` to the command line and provide paths to OpenMP headers and library with `-I <path to omp.h> -L <LLVM OpenMP library path>`.

Am I doing something wrong? Or is it not supported by your cmake code, in which case I guess it could be added (relatively) easily? Happy to contribute in the second case.

I looked at your CI code and I see you use brew packaged `gcc`. However that's a bit of a show stopper for Python wheels because it appears to break backward compatibility with older Macs, and Python wheels should be as retro-compatible as possible.

Thanks!

**Comment by enzbus** [comment]
Found the issue, in case you're interested. It's [discussed here](https://discourse.cmake.org/t/how-to-find-openmp-with-clang-on-macos/8860) and the solution [should be this](https://gist.github.com/scivision/16c2ca1dc250f54d34f1a1a35596f4a0), it's a cmake and clang issue, no changes needed on your code.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the note. Yes, I've gotten the libomp to work with clang on my M1 MacBook Air. I forget the details but once I installed it, I could use OpenMP in my suitesparse cmake without any changes to the cmake scripts. I think I  have a comment about that in my READMEs somewhere. Perhaps my GraphBLAS user guide.

**Comment by mmuetzel** [comment]
For the sake of completeness; The CI rules are building with Apple Clang and OpenMP.
`gcc` is only installed to have `gfortran` (which is optional and you can also build without it).
To point CMake to the OpenMP installation (among other dependencies that are installed at a "non-default" prefix), the flag `-DCMAKE_PREFIX_PATH="${HOMEBREW_PREFIX}/opt/lapack;${HOMEBREW_PREFIX}/opt/openblas;${HOMEBREW_PREFIX}/opt/libomp"` is set.

**Comment by enzbus** [comment]
Thank you! And sorry @mmuetzel , I haven't looked deeply in the CI/CD code. I link to Accelerate on Mac, to make smaller CPython wheels. If `openBLAS` is faster I can revisit that choice. With `brew install libomp` and setting environment variable `OpenMP_ROOT=$(brew --prefix)/opt/libomp` it works. Sadly the `libomp` from `brew` appears to be compiled on MacOS 14, the version Github CI runners have, without the `MACOSX_DEPLOYMENT_TARGET` variable by `cmake` to make it retro-compatible with older Macs. Not sure why `clang` doesn't ship with the `openMP` runtime libraries.

**Comment by DrTimothyAldenDavis** [comment]
> Not sure why `clang` doesn't ship with the `openMP` runtime libraries.

That's a decision by Apple that I've long puzzled about.  I suppose it's because they want developers on the Mac to use the Apple frameworks instead of OpenMP (like Apple Accelerate).  See for example: https://developer.apple.com/documentation/apple-silicon/tuning-your-code-s-performance-for-apple-silicon

**Comment by enzbus** [comment]
Makes sense. I'm quite impressed by what they've achieved with the aarch64 Macs. In my only other experience with arm computers (raspberry pi) I remember lackluster BLAS/LAPACK performance. As long as they keep exposing the open APIs I guess it's all good. (In fact thanks to Accelerate it's often straightforward to package scientific software on Mac, in my experience).
