### ISSUE TITLE
Allow re-use of factorization on multiple threads

### ISSUE THREAD

**Issue by adamConnerSax** [DrTimothyAldenDavis/SuiteSparse#9]
I'm using CHOLMOD (via Haskell, but I don't think that's important here) and I'd like to analyze a matrix structure once and then re-factor on multiple threads.  I tried this, using ```copy_factor``` to make a factor for each thread, and it failed with various seg-faults and other complaints from which I concluded/guessed that there must be some workspace in Common that is being re-used (?).  

So for now I've "solved" this by re-analyzing once per cpu and keeping a concurrent queue of common/factor pairs which get re-used by the various threads.  But that is clearly a waste of work.  

Is there any way to analyze just once and then make the rest of this work?

Thanks!

**Comment by DrTimothyAldenDavis** [comment]
There is workspace in the cholmod_common object that gets used during
factorization, so it's not thread-safe to use the same Common object for 2
concurrent calls to CHOLMOD.

The reuse is just pre-initialized space; there's no content in there.  So
it should be possible to do the analysis once and then reuse that object in
parallel calls later on.  But I haven't tried this so I'm not sure if that
would work.

**Comment by adamConnerSax** [comment]
If I understand you correctly, you're saying that there is workspace in ```Common``` that is used when factorizing or solving. 

So if I could somehow copy ```Common``` after analysis, I could use that?  That makes sense, but there's no library function to do that, right?  Or am I missing some straightforward way to copy the Common/Factor pair?

Or are you imagining parallel use where there is some locking around the common and factor objects?

Thanks!

**Comment by DrTimothyAldenDavis** [comment]
Yes, Common has workspace that is used for all CHOLMOD functions, so no
CHOLMOD function can be called in parallel by 2 user threads, unless they
have different Common objects.

You shouldn't need to make a copy of it (and I have no function for that).
You should be able to create a new Common object with cholmod_start, but I
haven't tried that yet.

**Comment by adamConnerSax** [comment]
Oh! You mean I could use the same factor and common objects created but without re-analysis?  All the analysis content is in the factor?  And I don't need to copy it because it has no workspace?
So what you would try is:
1. Use cholmod_start n times to create n common objects.  Set anything that needs setting.
2. Use 1 of them to analyze the problem and get the factor for my matrix structure.
3. For factorize and solve calls on a thread, use that same factor,  but a thread specific common object from the pool created above.

Is that correct?  I can try that!

**Comment by DrTimothyAldenDavis** [comment]
Yes, the analysis is inside the factor itself, not in the Common.  So I
think that approach should work (but I haven't tried it).

**Comment by adamConnerSax** [comment]
On first attempt, that doesn't appear to work.  I get similar errors as I did when re-using both common and factor.  I might also try with copied factors (using both original and new common in the copy call?) just in case that works.  

I'll close this.  You can re-open if you're interested in figuring out how to do it.  It would be useful in cases like mine but maybe that's rare.

Thanks for all the prompt responses!
