### ISSUE TITLE
Errors during SuiteSparse (Mongoose) installation on MATLAB

### ISSUE THREAD

**Issue by oleander12** [DrTimothyAldenDavis/SuiteSparse#97]
Dear SparseSparse developers and users, 

I tried to install SuiteSparse 5.10.1 on MATLAB but got an error during Mongoose installation. I am not sure if this is a bug or an error from my own side. I request your opinion. FYI, I use MATLAB 2021a update 4 on Windows 10 Pro. The system has Intel i7 CPU and Nvidia GPU. MATLAB uses Visual Studio 2019a as a compiler suite. I had to remove metis directory. Hope that I can use Mongoose along with SuiteSparse. In advance, thank you very much for reading this post. 

Best,
Evan

Compiling sparseinv (64-bit)
Building with 'Microsoft Visual C++ 2019 (C)'.
MEX completed successfully.
....Mongoose_CSparse.cpp
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2672: 'std::max': no matching overloaded function found
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2780: '_Ty std::max(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(52): note: see declaration of 'std::max'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2784: '_Ty std::max(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'csi'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(49): note: see declaration of 'std::max'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2782: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(41): note: see declaration of 'std::max'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): note: could be 'long'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): note: or       'csi'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2784: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'long'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(41): note: see declaration of 'std::max'
C:\MATLAB\R2021a\SuiteSparse-5.10.1\Mongoose\Source\Mongoose_CSparse.cpp(269): error C2780: 'const _Ty &std::max(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(32): note: see declaration of 'std::max'

**Comment by DrTimothyAldenDavis** [comment]
Both Microsoft (in Visual Studio) and MathWorks (in the MATLAB mex command and the compilation process) change things from time to time, in ways that break my codes on Windows, always in very unusual ways.  I don't use Windows myself so this is very difficult to keep up with.  Have you tried an older version of MATLAB?

**Comment by oleander12** [comment]
Thanks Professor Davis for your kind reply. I attempted to install the latest SuiteSparse library on both MATLAB 2018 and 2021 but was not successful.  In both trials, I had to remove metis 5.0 to avoid another types of errors. I was able to install a very old SuiteSparse library (version 3.6.1) on both MATLAB, but couldn't figure out what made this difference.

Best,
Evan

**Comment by DrTimothyAldenDavis** [comment]
I'm not able to support Windows since I don't use it myself, so I can't guarantee that the codes will work on Windows.  In particular, MS Visual Studio tends to break the ANSI C and C++ standards in unusual ways, and I can't keep up with their changes.
